#lang racket/base

;;;
;;; PROLOGOS QTT
;;; Quantitative Type Theory: multiplicity tracking layered on top of core typing.
;;; Direct translation of prologos-qtt.maude.
;;;
;;; The QTT layer tracks how each variable is used (0, 1, or ω times)
;;; and verifies that actual usage is compatible with declared multiplicities.
;;;
;;; UsageCtx: a list of multiplicities parallel to Context, where position k
;;; records how many times bvar(k) has been used.
;;;
;;; inferQ(ctx, e) -> TypeUsage(type, usage)  or tu-error
;;; checkQ(ctx, e, T) -> BoolUsage(bool, usage)
;;;

(require racket/match
         racket/list
         "prelude.rkt"
         "syntax.rkt"
         "substitution.rkt"
         "reduction.rkt"
         "unify.rkt"
         "typing-core.rkt"
         "metavar-store.rkt"
         "elab-speculation-bridge.rkt"
         "global-env.rkt")

(provide
 ;; Usage context operations
 zero-usage single-usage add-usage scale-usage
 uhead utail ulen
 check-all-usages
 ;; Result types
 (struct-out tu) (struct-out tu-error) (struct-out bu)
 ;; QTT inference and checking
 inferQ checkQ checkQ-top)

;; ========================================
;; Usage Context: plain list of multiplicities
;; ========================================

;; Create a zero-usage context of length n
(define (zero-usage n)
  (make-list n 'm0))

;; Create a usage with m1 at position k, m0 elsewhere, length n
(define (single-usage k n)
  (for/list ([i (in-range n)])
    (if (= i k) 'm1 'm0)))

;; Pointwise addition of usage contexts
(define (add-usage u1 u2)
  (cond
    [(and (null? u1) (null? u2)) '()]
    [(null? u1) u2]
    [(null? u2) u1]
    [else (cons (mult-add (car u1) (car u2))
                (add-usage (cdr u1) (cdr u2)))]))

;; Scalar multiplication of usage context
(define (scale-usage m u)
  (map (lambda (x) (mult-mul m x)) u))

;; Head and tail
(define (uhead u) (car u))
(define (utail u) (cdr u))

;; Length
(define (ulen u) (length u))

;; ========================================
;; Check that actual usages are compatible with declared multiplicities
;; ========================================
(define (check-all-usages ctx usage)
  (cond
    [(and (null? ctx) (null? usage)) #t]
    [(or (null? ctx) (null? usage)) #f]
    [else
     (let ([decl-mult (cdar ctx)]   ; multiplicity from context binding
           [actual (car usage)])
       (and (compatible decl-mult actual)
            (check-all-usages (cdr ctx) (cdr usage))))]))

;; ========================================
;; Result types for QTT inference and checking
;; ========================================
(struct tu (type usage) #:transparent)       ; type + usage
(struct tu-error () #:transparent)           ; inference failed
(struct bu (ok? usage) #:transparent)        ; bool + usage

;; tu-type and tu-usage are auto-generated by the struct definition.
;; For tu-error, use (match r [(tu t u) ...] [(tu-error) ...]) patterns.

;; Helper
(define (cdar x) (cdr (car x)))

;; Helper: try inferQ for f, fall back to checkQ with expected-type if inferQ fails.
;; This handles both named functions (inferQ works) and lambdas (need checkQ).
(define (inferQ-or-checkQ ctx f expected-f-type)
  (let ([r (inferQ ctx f)])
    (match r
      [(tu _ _) r]
      [(tu-error)
       (let ([rc (checkQ ctx f expected-f-type)])
         (match rc
           [(bu #t u) (tu expected-f-type u)]
           [_ (tu-error)]))])))

;; ========================================
;; QTT inference: inferQ(ctx, e) -> TypeUsage
;; ========================================
(define (inferQ ctx e)
  (define n (ctx-len ctx))
  (match e
    ;; ---- Variable: bvar(K) uses position K exactly once ----
    [(expr-bvar k)
     (if (< k n)
         (tu (shift (+ k 1) 0 (lookup-type k ctx))
             (single-usage k n))
         (tu-error))]

    ;; ---- Free variable: look up global environment ----
    ;; Global references do not consume local linear resources.
    [(expr-fvar name)
     (let ([ty (global-env-lookup-type name)])
       (if ty
           (tu ty (zero-usage n))
           (tu-error)))]

    ;; ---- Constants: zero usage ----
    [(expr-Type l) (tu (expr-Type (lsuc l)) (zero-usage n))]
    [(expr-Nat) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-Bool) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-zero) (tu (expr-Nat) (zero-usage n))]
    [(expr-nat-val _) (tu (expr-Nat) (zero-usage n))]
    [(expr-true) (tu (expr-Bool) (zero-usage n))]
    [(expr-false) (tu (expr-Bool) (zero-usage n))]
    [(expr-Unit) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-unit) (tu (expr-Unit) (zero-usage n))]
    [(expr-Nil) (tu (expr-Type (lzero)) (zero-usage n))]
    ;; nil value: type is Nil (the nullable type).
    ;; Note: when List's nil constructor is loaded, the elaborator produces (expr-fvar 'nil)
    ;; instead — this case only fires for bare Nil usage without List loaded.
    [(expr-nil) (tu (expr-Nil) (zero-usage n))]
    [(expr-Int) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-int _) (tu (expr-Int) (zero-usage n))]
    [(expr-Rat) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-rat _) (tu (expr-Rat) (zero-usage n))]
    [(expr-Posit8) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-posit8 _) (tu (expr-Posit8) (zero-usage n))]
    ;; Posit16
    [(expr-Posit16) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-posit16 _) (tu (expr-Posit16) (zero-usage n))]
    ;; Posit32
    [(expr-Posit32) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-posit32 _) (tu (expr-Posit32) (zero-usage n))]
    ;; Posit64
    [(expr-Posit64) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-posit64 _) (tu (expr-Posit64) (zero-usage n))]
    ;; Quire types and values (zero-usage: type formers and literals)
    [(expr-Quire8) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-quire8-val _) (tu (expr-Quire8) (zero-usage n))]
    [(expr-Quire16) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-quire16-val _) (tu (expr-Quire16) (zero-usage n))]
    [(expr-Quire32) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-quire32-val _) (tu (expr-Quire32) (zero-usage n))]
    [(expr-Quire64) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-quire64-val _) (tu (expr-Quire64) (zero-usage n))]

    ;; Unapplied type constructor (HKT) — zero usage, kind from kind table
    [(expr-tycon _) (tu (infer ctx e) (zero-usage n))]

    ;; ---- Type formers: Pi, Sigma, Eq ----
    ;; Type formers inhabit Type. Usage comes from sub-terms.
    ;; For top-level QTT checking of closed terms, these will have zero usage.
    [(expr-Pi m a b)
     (let ([r1 (inferQ ctx a)])
       (match r1
         [(tu _ u1)
          (let ([r2 (inferQ (ctx-extend ctx a m) b)])
            (match r2
              [(tu _ u2)
               (tu (expr-Type (lzero)) (add-usage u1 (utail u2)))]
              [_ (tu-error)]))]
         [_ (tu-error)]))]
    [(expr-Sigma a b)
     (let ([r1 (inferQ ctx a)])
       (match r1
         [(tu _ u1)
          (let ([r2 (inferQ (ctx-extend ctx a 'mw) b)])
            (match r2
              [(tu _ u2)
               (tu (expr-Type (lzero)) (add-usage u1 (utail u2)))]
              [_ (tu-error)]))]
         [_ (tu-error)]))]
    [(expr-Eq ty e1 e2)
     (let* ([r1 (inferQ ctx ty)]
            [r2 (inferQ ctx e1)]
            [r3 (inferQ ctx e2)])
       (match* (r1 r2 r3)
         [((tu _ u1) (tu _ u2) (tu _ u3))
          (tu (expr-Type (lzero)) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]

    ;; ---- Suc: usage from the argument ----
    [(expr-suc e1)
     (let ([r (inferQ ctx e1)])
       (match r
         [(tu (expr-Nat) u) (tu (expr-Nat) u)]
         [_ (tu-error)]))]

    ;; ---- Annotation: ann(e, T) ----
    [(expr-ann e1 t)
     (if (is-type ctx t)
         (let ([r (checkQ ctx e1 t)])
           (match r
             [(bu #t u) (tu t u)]
             [_ (tu-error)]))
         (tu-error))]

    ;; ---- Application ----
    ;; Usage = U_func + pi * U_arg
    [(expr-app e1 e2)
     (match e1
       ;; Special case: app(lam(m, dom, body), arg) — beta-typed application
       ;; This supports let-expansion: (let x := v body) = app(lam(m, dom, body), v)
       [(expr-lam m dom body)
        (let ([arg-dom (if (or (expr-hole? dom) (expr-typed-hole? dom))
                           ;; Infer arg type for hole domain
                           (let ([ri (inferQ ctx e2)])
                             (match ri [(tu t _) t] [_ #f]))
                           dom)])
          (if (not arg-dom)
              (tu-error)
              (let ([r2 (checkQ ctx e2 arg-dom)])
                (match r2
                  [(bu #t u2)
                   (let ([r-body (inferQ (ctx-extend ctx arg-dom m) body)])
                     (match r-body
                       [(tu body-ty u-body)
                        (tu (subst 0 e2 body-ty)
                            (add-usage (scale-usage m u2) (utail u-body)))]
                       [_ (tu-error)]))]
                  [_ (tu-error)]))))]
       ;; General case: infer function type, check argument
       [_
        (let ([r1 (inferQ ctx e1)])
          (match r1
            [(tu t1 u1)
             (match (whnf t1)
               [(expr-Pi m a b)
                (let ([r2 (checkQ ctx e2 a)])
                  (match r2
                    [(bu #t u2)
                     (tu (subst 0 e2 b) (add-usage u1 (scale-usage m u2)))]
                    [_ (tu-error)]))]
               [_ (tu-error)])]
            [_ (tu-error)]))])]

    ;; ---- fst ----
    [(expr-fst e1)
     (let ([r (inferQ ctx e1)])
       (match r
         [(tu t u)
          (match (whnf t)
            [(expr-Sigma a _) (tu a u)]
            [_ (tu-error)])]
         [_ (tu-error)]))]

    ;; ---- snd ----
    [(expr-snd e1)
     (let ([r (inferQ ctx e1)])
       (match r
         [(tu t u)
          (match (whnf t)
            [(expr-Sigma _ b) (tu (subst 0 (expr-fst e1) b) u)]
            [_ (tu-error)])]
         [_ (tu-error)]))]

    ;; ---- natrec ----
    ;; Usage = U_target + U_base + U_step (motive is type-level)
    [(expr-natrec mot base step target)
     (let ([step-type
            ;; Π(n:Nat). motive(n) → motive(suc(n))
            (expr-Pi 'mw (expr-Nat)
              (expr-Pi 'mw (expr-app (shift 1 0 mot) (expr-bvar 0))
                (expr-app (shift 2 0 mot) (expr-suc (expr-bvar 1)))))])
       (let ([r4 (checkQ ctx target (expr-Nat))])
         (match r4
           [(bu #t u4)
            (let ([r2 (checkQ ctx base (expr-app mot (expr-zero)))])
              (match r2
                [(bu #t u2)
                 (let ([r3 (checkQ ctx step step-type)])
                   (match r3
                     [(bu #t u3)
                      (tu (expr-app mot target)
                          (add-usage u4 (add-usage u2 u3)))]
                     [_ (tu-error)]))]
                [_ (tu-error)]))]
           [_ (tu-error)])))]

    ;; ---- boolrec ----
    ;; Usage = U_target + U_true-case + U_false-case (motive is type-level)
    ;; boolrec(motive, true-case, false-case, target)
    [(expr-boolrec mot tc fc target)
     (let ([r4 (checkQ ctx target (expr-Bool))])
       (match r4
         [(bu #t u4)
          (let ([r2 (checkQ ctx tc (expr-app mot (expr-true)))])
            (match r2
              [(bu #t u2)
               (let ([r3 (checkQ ctx fc (expr-app mot (expr-false)))])
                 (match r3
                   [(bu #t u3)
                    (tu (expr-app mot target)
                        (add-usage u4 (add-usage u2 u3)))]
                   [_ (tu-error)]))]
              [_ (tu-error)]))]
         [_ (tu-error)]))]

    ;; ---- Int binary operations ----
    ;; Binary ops: Int -> Int -> Int
    [(expr-int-add a b)
     (let ([r1 (checkQ ctx a (expr-Int))]
           [r2 (checkQ ctx b (expr-Int))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Int) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-int-sub a b)
     (let ([r1 (checkQ ctx a (expr-Int))]
           [r2 (checkQ ctx b (expr-Int))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Int) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-int-mul a b)
     (let ([r1 (checkQ ctx a (expr-Int))]
           [r2 (checkQ ctx b (expr-Int))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Int) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-int-div a b)
     (let ([r1 (checkQ ctx a (expr-Int))]
           [r2 (checkQ ctx b (expr-Int))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Int) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-int-mod a b)
     (let ([r1 (checkQ ctx a (expr-Int))]
           [r2 (checkQ ctx b (expr-Int))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Int) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; Unary Int ops: Int -> Int
    [(expr-int-neg a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Int) u) (tu (expr-Int) u)] [_ (tu-error)]))]
    [(expr-int-abs a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Int) u) (tu (expr-Int) u)] [_ (tu-error)]))]

    ;; Int comparisons: Int -> Int -> Bool
    [(expr-int-lt a b)
     (let ([r1 (checkQ ctx a (expr-Int))]
           [r2 (checkQ ctx b (expr-Int))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-int-le a b)
     (let ([r1 (checkQ ctx a (expr-Int))]
           [r2 (checkQ ctx b (expr-Int))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-int-eq a b)
     (let ([r1 (checkQ ctx a (expr-Int))]
           [r2 (checkQ ctx b (expr-Int))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; Int conversion: Nat -> Int
    [(expr-from-nat e1)
     (let ([r (checkQ ctx e1 (expr-Nat))])
       (match r [(bu #t u) (tu (expr-Int) u)] [_ (tu-error)]))]

    ;; ---- Rat binary operations ----
    ;; Binary ops: Rat -> Rat -> Rat
    [(expr-rat-add a b)
     (let ([r1 (checkQ ctx a (expr-Rat))]
           [r2 (checkQ ctx b (expr-Rat))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Rat) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-rat-sub a b)
     (let ([r1 (checkQ ctx a (expr-Rat))]
           [r2 (checkQ ctx b (expr-Rat))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Rat) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-rat-mul a b)
     (let ([r1 (checkQ ctx a (expr-Rat))]
           [r2 (checkQ ctx b (expr-Rat))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Rat) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-rat-div a b)
     (let ([r1 (checkQ ctx a (expr-Rat))]
           [r2 (checkQ ctx b (expr-Rat))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Rat) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; Unary Rat ops: Rat -> Rat
    [(expr-rat-neg a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Rat) u) (tu (expr-Rat) u)] [_ (tu-error)]))]
    [(expr-rat-abs a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Rat) u) (tu (expr-Rat) u)] [_ (tu-error)]))]

    ;; Rat comparisons: Rat -> Rat -> Bool
    [(expr-rat-lt a b)
     (let ([r1 (checkQ ctx a (expr-Rat))]
           [r2 (checkQ ctx b (expr-Rat))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-rat-le a b)
     (let ([r1 (checkQ ctx a (expr-Rat))]
           [r2 (checkQ ctx b (expr-Rat))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-rat-eq a b)
     (let ([r1 (checkQ ctx a (expr-Rat))]
           [r2 (checkQ ctx b (expr-Rat))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; Rat conversion: Int -> Rat
    [(expr-from-int e1)
     (let ([r (checkQ ctx e1 (expr-Int))])
       (match r [(bu #t u) (tu (expr-Rat) u)] [_ (tu-error)]))]

    ;; Rat projections: Rat -> Int
    [(expr-rat-numer a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Rat) u) (tu (expr-Int) u)] [_ (tu-error)]))]
    [(expr-rat-denom a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Rat) u) (tu (expr-Int) u)] [_ (tu-error)]))]

    ;; ---- Generic arithmetic operators ----
    ;; Binary arithmetic: infer both args, return same type
    [(expr-generic-add a b)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx b)])
       (match* (r1 r2)
         [((tu t1 u1) (tu t2 u2))
          (if (and (equal? t1 t2) (concrete-numeric-type? t1))
              (tu t1 (add-usage u1 u2))
              (tu-error))]
         [(_ _) (tu-error)]))]
    [(expr-generic-sub a b)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx b)])
       (match* (r1 r2)
         [((tu t1 u1) (tu t2 u2))
          (if (and (equal? t1 t2) (concrete-numeric-type? t1))
              (tu t1 (add-usage u1 u2))
              (tu-error))]
         [(_ _) (tu-error)]))]
    [(expr-generic-mul a b)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx b)])
       (match* (r1 r2)
         [((tu t1 u1) (tu t2 u2))
          (if (and (equal? t1 t2) (concrete-numeric-type? t1))
              (tu t1 (add-usage u1 u2))
              (tu-error))]
         [(_ _) (tu-error)]))]
    [(expr-generic-div a b)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx b)])
       (match* (r1 r2)
         [((tu t1 u1) (tu t2 u2))
          (if (and (equal? t1 t2) (divisible-numeric-type? t1))
              (tu t1 (add-usage u1 u2))
              (tu-error))]
         [(_ _) (tu-error)]))]

    ;; Binary comparison: infer both args, return Bool
    [(expr-generic-lt a b)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx b)])
       (match* (r1 r2)
         [((tu t1 u1) (tu t2 u2))
          (if (and (equal? t1 t2) (concrete-numeric-type? t1))
              (tu (expr-Bool) (add-usage u1 u2))
              (tu-error))]
         [(_ _) (tu-error)]))]
    [(expr-generic-le a b)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx b)])
       (match* (r1 r2)
         [((tu t1 u1) (tu t2 u2))
          (if (and (equal? t1 t2) (concrete-numeric-type? t1))
              (tu (expr-Bool) (add-usage u1 u2))
              (tu-error))]
         [(_ _) (tu-error)]))]
    [(expr-generic-gt a b)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx b)])
       (match* (r1 r2)
         [((tu t1 u1) (tu t2 u2))
          (if (and (equal? t1 t2) (concrete-numeric-type? t1))
              (tu (expr-Bool) (add-usage u1 u2))
              (tu-error))]
         [(_ _) (tu-error)]))]
    [(expr-generic-ge a b)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx b)])
       (match* (r1 r2)
         [((tu t1 u1) (tu t2 u2))
          (if (and (equal? t1 t2) (concrete-numeric-type? t1))
              (tu (expr-Bool) (add-usage u1 u2))
              (tu-error))]
         [(_ _) (tu-error)]))]
    [(expr-generic-eq a b)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx b)])
       (match* (r1 r2)
         [((tu t1 u1) (tu t2 u2))
          (if (and (equal? t1 t2) (concrete-numeric-type? t1))
              (tu (expr-Bool) (add-usage u1 u2))
              (tu-error))]
         [(_ _) (tu-error)]))]
    [(expr-generic-mod a b)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx b)])
       (match* (r1 r2)
         [((tu t1 u1) (tu t2 u2))
          (if (and (equal? t1 t2) (concrete-numeric-type? t1))
              (tu t1 (add-usage u1 u2))
              (tu-error))]
         [(_ _) (tu-error)]))]

    ;; Unary: infer arg, return same type
    [(expr-generic-negate a)
     (let ([r (inferQ ctx a)])
       (match r
         [(tu t u) (if (negatable-numeric-type? t) (tu t u) (tu-error))]
         [_ (tu-error)]))]
    [(expr-generic-abs a)
     (let ([r (inferQ ctx a)])
       (match r
         [(tu t u) (if (concrete-numeric-type? t) (tu t u) (tu-error))]
         [_ (tu-error)]))]

    ;; Generic conversion: from-integer TargetType val, from-rational TargetType val
    ;; target-type is erased (it's a type), usage comes from the arg
    [(expr-generic-from-int target-type arg)
     (let ([r (checkQ ctx arg (expr-Int))])
       (match r
         [(bu #t u) (if (from-int-target-type? target-type)
                        (tu target-type u)
                        (tu-error))]
         [_ (tu-error)]))]
    [(expr-generic-from-rat target-type arg)
     (let ([r (checkQ ctx arg (expr-Rat))])
       (match r
         [(bu #t u) (if (from-rat-target-type? target-type)
                        (tu target-type u)
                        (tu-error))]
         [_ (tu-error)]))]

    ;; ---- Posit8 binary operations ----
    ;; Binary ops: Posit8 -> Posit8 -> Posit8
    [(expr-p8-add a b)
     (let ([r1 (checkQ ctx a (expr-Posit8))]
           [r2 (checkQ ctx b (expr-Posit8))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit8) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p8-sub a b)
     (let ([r1 (checkQ ctx a (expr-Posit8))]
           [r2 (checkQ ctx b (expr-Posit8))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit8) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p8-mul a b)
     (let ([r1 (checkQ ctx a (expr-Posit8))]
           [r2 (checkQ ctx b (expr-Posit8))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit8) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p8-div a b)
     (let ([r1 (checkQ ctx a (expr-Posit8))]
           [r2 (checkQ ctx b (expr-Posit8))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit8) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; Unary Posit8 ops: Posit8 -> Posit8
    [(expr-p8-neg a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Posit8) u) (tu (expr-Posit8) u)] [_ (tu-error)]))]
    [(expr-p8-abs a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Posit8) u) (tu (expr-Posit8) u)] [_ (tu-error)]))]
    [(expr-p8-sqrt a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Posit8) u) (tu (expr-Posit8) u)] [_ (tu-error)]))]

    ;; Posit8 comparisons: Posit8 -> Posit8 -> Bool
    [(expr-p8-lt a b)
     (let ([r1 (checkQ ctx a (expr-Posit8))]
           [r2 (checkQ ctx b (expr-Posit8))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p8-le a b)
     (let ([r1 (checkQ ctx a (expr-Posit8))]
           [r2 (checkQ ctx b (expr-Posit8))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p8-eq a b)
     (let ([r1 (checkQ ctx a (expr-Posit8))]
           [r2 (checkQ ctx b (expr-Posit8))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; Posit8 conversion: Nat -> Posit8
    [(expr-p8-from-nat e1)
     (let ([r (checkQ ctx e1 (expr-Nat))])
       (match r [(bu #t u) (tu (expr-Posit8) u)] [_ (tu-error)]))]

    ;; Phase 3f: Cross-family conversions for Posit8
    [(expr-p8-to-rat e1)
     (let ([r (checkQ ctx e1 (expr-Posit8))])
       (match r [(bu #t u) (tu (expr-Rat) u)] [_ (tu-error)]))]
    [(expr-p8-from-rat e1)
     (let ([r (checkQ ctx e1 (expr-Rat))])
       (match r [(bu #t u) (tu (expr-Posit8) u)] [_ (tu-error)]))]
    [(expr-p8-from-int e1)
     (let ([r (checkQ ctx e1 (expr-Int))])
       (match r [(bu #t u) (tu (expr-Posit8) u)] [_ (tu-error)]))]

    ;; Posit8 NaR eliminator: p8-if-nar(A, nar-case, normal-case, val)
    [(expr-p8-if-nar ty nar-case normal-case val)
     (let ([r4 (checkQ ctx val (expr-Posit8))])
       (match r4
         [(bu #t u4)
          (let ([r2 (checkQ ctx nar-case ty)])
            (match r2
              [(bu #t u2)
               (let ([r3 (checkQ ctx normal-case ty)])
                 (match r3
                   [(bu #t u3)
                    (tu ty (add-usage u4 (add-usage u2 u3)))]
                   [_ (tu-error)]))]
              [_ (tu-error)]))]
         [_ (tu-error)]))]

    ;; ---- Posit16 binary operations ----
    ;; Binary ops: Posit16 -> Posit16 -> Posit16
    [(expr-p16-add a b)
     (let ([r1 (checkQ ctx a (expr-Posit16))]
           [r2 (checkQ ctx b (expr-Posit16))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit16) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p16-sub a b)
     (let ([r1 (checkQ ctx a (expr-Posit16))]
           [r2 (checkQ ctx b (expr-Posit16))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit16) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p16-mul a b)
     (let ([r1 (checkQ ctx a (expr-Posit16))]
           [r2 (checkQ ctx b (expr-Posit16))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit16) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p16-div a b)
     (let ([r1 (checkQ ctx a (expr-Posit16))]
           [r2 (checkQ ctx b (expr-Posit16))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit16) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; Unary Posit16 ops: Posit16 -> Posit16
    [(expr-p16-neg a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Posit16) u) (tu (expr-Posit16) u)] [_ (tu-error)]))]
    [(expr-p16-abs a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Posit16) u) (tu (expr-Posit16) u)] [_ (tu-error)]))]
    [(expr-p16-sqrt a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Posit16) u) (tu (expr-Posit16) u)] [_ (tu-error)]))]

    ;; Posit16 comparisons: Posit16 -> Posit16 -> Bool
    [(expr-p16-lt a b)
     (let ([r1 (checkQ ctx a (expr-Posit16))]
           [r2 (checkQ ctx b (expr-Posit16))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p16-le a b)
     (let ([r1 (checkQ ctx a (expr-Posit16))]
           [r2 (checkQ ctx b (expr-Posit16))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p16-eq a b)
     (let ([r1 (checkQ ctx a (expr-Posit16))]
           [r2 (checkQ ctx b (expr-Posit16))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; Posit16 conversion: Nat -> Posit16
    [(expr-p16-from-nat e1)
     (let ([r (checkQ ctx e1 (expr-Nat))])
       (match r [(bu #t u) (tu (expr-Posit16) u)] [_ (tu-error)]))]

    ;; Phase 3f: Cross-family conversions for Posit16
    [(expr-p16-to-rat e1)
     (let ([r (checkQ ctx e1 (expr-Posit16))])
       (match r [(bu #t u) (tu (expr-Rat) u)] [_ (tu-error)]))]
    [(expr-p16-from-rat e1)
     (let ([r (checkQ ctx e1 (expr-Rat))])
       (match r [(bu #t u) (tu (expr-Posit16) u)] [_ (tu-error)]))]
    [(expr-p16-from-int e1)
     (let ([r (checkQ ctx e1 (expr-Int))])
       (match r [(bu #t u) (tu (expr-Posit16) u)] [_ (tu-error)]))]

    ;; Posit16 NaR eliminator: p16-if-nar(A, nar-case, normal-case, val)
    [(expr-p16-if-nar ty nar-case normal-case val)
     (let ([r4 (checkQ ctx val (expr-Posit16))])
       (match r4
         [(bu #t u4)
          (let ([r2 (checkQ ctx nar-case ty)])
            (match r2
              [(bu #t u2)
               (let ([r3 (checkQ ctx normal-case ty)])
                 (match r3
                   [(bu #t u3)
                    (tu ty (add-usage u4 (add-usage u2 u3)))]
                   [_ (tu-error)]))]
              [_ (tu-error)]))]
         [_ (tu-error)]))]

    ;; ---- Posit32 binary operations ----
    ;; Binary ops: Posit32 -> Posit32 -> Posit32
    [(expr-p32-add a b)
     (let ([r1 (checkQ ctx a (expr-Posit32))]
           [r2 (checkQ ctx b (expr-Posit32))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit32) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p32-sub a b)
     (let ([r1 (checkQ ctx a (expr-Posit32))]
           [r2 (checkQ ctx b (expr-Posit32))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit32) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p32-mul a b)
     (let ([r1 (checkQ ctx a (expr-Posit32))]
           [r2 (checkQ ctx b (expr-Posit32))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit32) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p32-div a b)
     (let ([r1 (checkQ ctx a (expr-Posit32))]
           [r2 (checkQ ctx b (expr-Posit32))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit32) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; Unary Posit32 ops: Posit32 -> Posit32
    [(expr-p32-neg a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Posit32) u) (tu (expr-Posit32) u)] [_ (tu-error)]))]
    [(expr-p32-abs a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Posit32) u) (tu (expr-Posit32) u)] [_ (tu-error)]))]
    [(expr-p32-sqrt a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Posit32) u) (tu (expr-Posit32) u)] [_ (tu-error)]))]

    ;; Posit32 comparisons: Posit32 -> Posit32 -> Bool
    [(expr-p32-lt a b)
     (let ([r1 (checkQ ctx a (expr-Posit32))]
           [r2 (checkQ ctx b (expr-Posit32))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p32-le a b)
     (let ([r1 (checkQ ctx a (expr-Posit32))]
           [r2 (checkQ ctx b (expr-Posit32))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p32-eq a b)
     (let ([r1 (checkQ ctx a (expr-Posit32))]
           [r2 (checkQ ctx b (expr-Posit32))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; Posit32 conversion: Nat -> Posit32
    [(expr-p32-from-nat e1)
     (let ([r (checkQ ctx e1 (expr-Nat))])
       (match r [(bu #t u) (tu (expr-Posit32) u)] [_ (tu-error)]))]

    ;; Phase 3f: Cross-family conversions for Posit32
    [(expr-p32-to-rat e1)
     (let ([r (checkQ ctx e1 (expr-Posit32))])
       (match r [(bu #t u) (tu (expr-Rat) u)] [_ (tu-error)]))]
    [(expr-p32-from-rat e1)
     (let ([r (checkQ ctx e1 (expr-Rat))])
       (match r [(bu #t u) (tu (expr-Posit32) u)] [_ (tu-error)]))]
    [(expr-p32-from-int e1)
     (let ([r (checkQ ctx e1 (expr-Int))])
       (match r [(bu #t u) (tu (expr-Posit32) u)] [_ (tu-error)]))]

    ;; Posit32 NaR eliminator: p32-if-nar(A, nar-case, normal-case, val)
    [(expr-p32-if-nar ty nar-case normal-case val)
     (let ([r4 (checkQ ctx val (expr-Posit32))])
       (match r4
         [(bu #t u4)
          (let ([r2 (checkQ ctx nar-case ty)])
            (match r2
              [(bu #t u2)
               (let ([r3 (checkQ ctx normal-case ty)])
                 (match r3
                   [(bu #t u3)
                    (tu ty (add-usage u4 (add-usage u2 u3)))]
                   [_ (tu-error)]))]
              [_ (tu-error)]))]
         [_ (tu-error)]))]

    ;; ---- Posit64 binary operations ----
    ;; Binary ops: Posit64 -> Posit64 -> Posit64
    [(expr-p64-add a b)
     (let ([r1 (checkQ ctx a (expr-Posit64))]
           [r2 (checkQ ctx b (expr-Posit64))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit64) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p64-sub a b)
     (let ([r1 (checkQ ctx a (expr-Posit64))]
           [r2 (checkQ ctx b (expr-Posit64))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit64) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p64-mul a b)
     (let ([r1 (checkQ ctx a (expr-Posit64))]
           [r2 (checkQ ctx b (expr-Posit64))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit64) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p64-div a b)
     (let ([r1 (checkQ ctx a (expr-Posit64))]
           [r2 (checkQ ctx b (expr-Posit64))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Posit64) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; Unary Posit64 ops: Posit64 -> Posit64
    [(expr-p64-neg a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Posit64) u) (tu (expr-Posit64) u)] [_ (tu-error)]))]
    [(expr-p64-abs a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Posit64) u) (tu (expr-Posit64) u)] [_ (tu-error)]))]
    [(expr-p64-sqrt a)
     (let ([r (inferQ ctx a)])
       (match r [(tu (expr-Posit64) u) (tu (expr-Posit64) u)] [_ (tu-error)]))]

    ;; Posit64 comparisons: Posit64 -> Posit64 -> Bool
    [(expr-p64-lt a b)
     (let ([r1 (checkQ ctx a (expr-Posit64))]
           [r2 (checkQ ctx b (expr-Posit64))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p64-le a b)
     (let ([r1 (checkQ ctx a (expr-Posit64))]
           [r2 (checkQ ctx b (expr-Posit64))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-p64-eq a b)
     (let ([r1 (checkQ ctx a (expr-Posit64))]
           [r2 (checkQ ctx b (expr-Posit64))])
       (match* (r1 r2)
         [((bu #t u1) (bu #t u2)) (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; Posit64 conversion: Nat -> Posit64
    [(expr-p64-from-nat e1)
     (let ([r (checkQ ctx e1 (expr-Nat))])
       (match r [(bu #t u) (tu (expr-Posit64) u)] [_ (tu-error)]))]

    ;; Phase 3f: Cross-family conversions for Posit64
    [(expr-p64-to-rat e1)
     (let ([r (checkQ ctx e1 (expr-Posit64))])
       (match r [(bu #t u) (tu (expr-Rat) u)] [_ (tu-error)]))]
    [(expr-p64-from-rat e1)
     (let ([r (checkQ ctx e1 (expr-Rat))])
       (match r [(bu #t u) (tu (expr-Posit64) u)] [_ (tu-error)]))]
    [(expr-p64-from-int e1)
     (let ([r (checkQ ctx e1 (expr-Int))])
       (match r [(bu #t u) (tu (expr-Posit64) u)] [_ (tu-error)]))]

    ;; Posit64 NaR eliminator: p64-if-nar(A, nar-case, normal-case, val)
    [(expr-p64-if-nar ty nar-case normal-case val)
     (let ([r4 (checkQ ctx val (expr-Posit64))])
       (match r4
         [(bu #t u4)
          (let ([r2 (checkQ ctx nar-case ty)])
            (match r2
              [(bu #t u2)
               (let ([r3 (checkQ ctx normal-case ty)])
                 (match r3
                   [(bu #t u3)
                    (tu ty (add-usage u4 (add-usage u2 u3)))]
                   [_ (tu-error)]))]
              [_ (tu-error)]))]
         [_ (tu-error)]))]

    ;; ---- Quire FMA operations ----
    ;; quireW-fma(q, a, b): usage = U_q + U_a + U_b
    [(expr-quire8-fma q a b)
     (let ([r1 (checkQ ctx q (expr-Quire8))]
           [r2 (checkQ ctx a (expr-Posit8))]
           [r3 (checkQ ctx b (expr-Posit8))])
       (match* (r1 r2 r3)
         [((bu #t u1) (bu #t u2) (bu #t u3))
          (tu (expr-Quire8) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]
    [(expr-quire16-fma q a b)
     (let ([r1 (checkQ ctx q (expr-Quire16))]
           [r2 (checkQ ctx a (expr-Posit16))]
           [r3 (checkQ ctx b (expr-Posit16))])
       (match* (r1 r2 r3)
         [((bu #t u1) (bu #t u2) (bu #t u3))
          (tu (expr-Quire16) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]
    [(expr-quire32-fma q a b)
     (let ([r1 (checkQ ctx q (expr-Quire32))]
           [r2 (checkQ ctx a (expr-Posit32))]
           [r3 (checkQ ctx b (expr-Posit32))])
       (match* (r1 r2 r3)
         [((bu #t u1) (bu #t u2) (bu #t u3))
          (tu (expr-Quire32) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]
    [(expr-quire64-fma q a b)
     (let ([r1 (checkQ ctx q (expr-Quire64))]
           [r2 (checkQ ctx a (expr-Posit64))]
           [r3 (checkQ ctx b (expr-Posit64))])
       (match* (r1 r2 r3)
         [((bu #t u1) (bu #t u2) (bu #t u3))
          (tu (expr-Quire64) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]

    ;; ---- Quire TO operations ----
    ;; quireW-to(q): usage = U_q
    [(expr-quire8-to q)
     (let ([r (checkQ ctx q (expr-Quire8))])
       (match r [(bu #t u) (tu (expr-Posit8) u)] [_ (tu-error)]))]
    [(expr-quire16-to q)
     (let ([r (checkQ ctx q (expr-Quire16))])
       (match r [(bu #t u) (tu (expr-Posit16) u)] [_ (tu-error)]))]
    [(expr-quire32-to q)
     (let ([r (checkQ ctx q (expr-Quire32))])
       (match r [(bu #t u) (tu (expr-Posit32) u)] [_ (tu-error)]))]
    [(expr-quire64-to q)
     (let ([r (checkQ ctx q (expr-Quire64))])
       (match r [(bu #t u) (tu (expr-Posit64) u)] [_ (tu-error)]))]

    ;; Symbol
    [(expr-Symbol) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-symbol _) (tu (expr-Symbol) (zero-usage n))]
    ;; Keyword
    [(expr-Keyword) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-keyword _) (tu (expr-Keyword) (zero-usage n))]
    ;; Path
    [(expr-Path) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-path _) (tu (expr-Path) (zero-usage n))]
    ;; Dynamic path operations
    [(expr-get-in target paths)
     (let ([r1 (inferQ ctx target)]
           [r2 (inferQ ctx paths)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (fresh-meta ctx-empty (expr-hole)
                (meta-source-info #f 'get-in-result "result type of dynamic get-in" #f '()))
              (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-update-in target paths fn)
     (let ([r1 (inferQ ctx target)]
           [r2 (inferQ ctx paths)]
           [r3 (inferQ ctx fn)])
       (match* (r1 r2 r3)
         [((tu t1 u1) (tu _ u2) (tu _ u3))
          (tu t1 (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]
    ;; Char
    [(expr-Char) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-char _) (tu (expr-Char) (zero-usage n))]
    ;; String
    [(expr-String) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-string _) (tu (expr-String) (zero-usage n))]
    ;; Map
    [(expr-Map k v)
     (let ([r1 (inferQ ctx k)]
           [r2 (inferQ ctx v)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (expr-Type (lzero)) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-champ _) (tu (expr-Map (expr-hole) (expr-hole)) (zero-usage n))]
    [(expr-map-empty k v)
     (let ([r1 (inferQ ctx k)]
           [r2 (inferQ ctx v)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (expr-Map k v) (scale-usage 'm0 (add-usage u1 u2)))]  ;; type args are erased
         [(_ _) (tu-error)]))]
    [(expr-map-assoc m k v)
     (let ([r1 (inferQ ctx m)]
           [r2 (inferQ ctx k)]
           [r3 (inferQ ctx v)])
       (match* (r1 r2 r3)
         [((tu _ u1) (tu _ u2) (tu _ u3))
          (tu (tu-type r1) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]
    [(expr-map-get m k)
     (let ([r1 (inferQ ctx m)]
           [r2 (inferQ ctx k)])
       (match* (r1 r2)
         [((tu t1 u1) (tu _ u2))
          ;; map-get returns the value type V from Map K V
          (match t1
            [(expr-Map _ vt) (tu vt (add-usage u1 u2))]
            ;; Schema/selection type: infer result type from typing-core, track usage
            [(expr-fvar name)
             #:when (or (lookup-schema-by-name name) (lookup-selection-by-name name))
             (let ([result-type (infer ctx e)])
               (tu result-type (add-usage u1 u2)))]
            [_ (tu-error)])]
         [(_ _) (tu-error)]))]
    [(expr-get c k)
     (let ([r1 (inferQ ctx c)]
           [r2 (inferQ ctx k)])
       (match* (r1 r2)
         [((tu t1 u1) (tu _ u2))
          ;; get: infer result type from typing-core, track usage from both args
          (let ([result-type (infer ctx e)])
            (tu result-type (add-usage u1 u2)))]
         [(_ _) (tu-error)]))]
    [(expr-nil-safe-get m k)
     (let ([r1 (inferQ ctx m)]
           [r2 (inferQ ctx k)])
       (match* (r1 r2)
         [((tu t1 u1) (tu _ u2))
          ;; nil-safe-get: infer type from typing-core, track usage from both args
          (let ([result-type (infer ctx e)])
            (tu result-type (add-usage u1 u2)))]
         [(_ _) (tu-error)]))]
    [(expr-nil-check arg)
     (let ([r (inferQ ctx arg)])
       (match r
         [(tu _ u) (tu (expr-Bool) u)]
         [_ (tu-error)]))]
    [(expr-map-dissoc m k)
     (let ([r1 (inferQ ctx m)]
           [r2 (inferQ ctx k)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (tu-type r1) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-map-size m)
     (let ([r (inferQ ctx m)])
       (match r
         [(tu _ u) (tu (expr-Nat) u)]
         [_ (tu-error)]))]
    [(expr-map-has-key m k)
     (let ([r1 (inferQ ctx m)]
           [r2 (inferQ ctx k)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-map-keys m)
     (let ([r (inferQ ctx m)])
       (match r
         [(tu _ u) (tu (infer ctx (expr-map-keys m)) u)]
         [_ (tu-error)]))]
    [(expr-map-vals m)
     (let ([r (inferQ ctx m)])
       (match r
         [(tu _ u) (tu (infer ctx (expr-map-vals m)) u)]
         [_ (tu-error)]))]

    ;; ---- Set type and operations ----
    [(expr-Set a)
     (let ([r (inferQ ctx a)])
       (match r
         [(tu _ u) (tu (expr-Type (lzero)) u)]
         [_ (tu-error)]))]
    [(expr-hset _) (tu (expr-Set (expr-hole)) (zero-usage n))]
    [(expr-set-empty a)
     (let ([r (inferQ ctx a)])
       (match r
         [(tu _ u) (tu (expr-Set a) (scale-usage 'm0 u))]  ;; type arg is erased
         [_ (tu-error)]))]
    [(expr-set-insert s a)
     (let ([r1 (inferQ ctx s)]
           [r2 (inferQ ctx a)])
       (match* (r1 r2)
         [((tu t1 u1) (tu _ u2))
          (match (whnf t1)
            [(expr-Set a-ty)
             (if (check ctx a a-ty)
                 (tu (expr-Set a-ty) (add-usage u1 u2))
                 (tu-error))]
            [_ (tu-error)])]
         [(_ _) (tu-error)]))]
    [(expr-set-member s a)
     (let ([r1 (inferQ ctx s)]
           [r2 (inferQ ctx a)])
       (match* (r1 r2)
         [((tu t1 u1) (tu _ u2))
          (match (whnf t1)
            [(expr-Set a-ty)
             (if (check ctx a a-ty)
                 (tu (expr-Bool) (add-usage u1 u2))
                 (tu-error))]
            [_ (tu-error)])]
         [(_ _) (tu-error)]))]
    [(expr-set-delete s a)
     (let ([r1 (inferQ ctx s)]
           [r2 (inferQ ctx a)])
       (match* (r1 r2)
         [((tu t1 u1) (tu _ u2))
          (match (whnf t1)
            [(expr-Set a-ty)
             (if (check ctx a a-ty)
                 (tu (expr-Set a-ty) (add-usage u1 u2))
                 (tu-error))]
            [_ (tu-error)])]
         [(_ _) (tu-error)]))]
    [(expr-set-size s)
     (let ([r (inferQ ctx s)])
       (match r
         [(tu _ u) (tu (expr-Nat) u)]
         [_ (tu-error)]))]
    [(expr-set-union s1 s2)
     (let ([r1 (inferQ ctx s1)]
           [r2 (inferQ ctx s2)])
       (match* (r1 r2)
         [((tu t1 u1) (tu _ u2))
          (match (whnf t1)
            [(expr-Set a-ty)
             (if (check ctx s2 (expr-Set a-ty))
                 (tu (expr-Set a-ty) (add-usage u1 u2))
                 (tu-error))]
            [_ (tu-error)])]
         [(_ _) (tu-error)]))]
    [(expr-set-intersect s1 s2)
     (let ([r1 (inferQ ctx s1)]
           [r2 (inferQ ctx s2)])
       (match* (r1 r2)
         [((tu t1 u1) (tu _ u2))
          (match (whnf t1)
            [(expr-Set a-ty)
             (if (check ctx s2 (expr-Set a-ty))
                 (tu (expr-Set a-ty) (add-usage u1 u2))
                 (tu-error))]
            [_ (tu-error)])]
         [(_ _) (tu-error)]))]
    [(expr-set-diff s1 s2)
     (let ([r1 (inferQ ctx s1)]
           [r2 (inferQ ctx s2)])
       (match* (r1 r2)
         [((tu t1 u1) (tu _ u2))
          (match (whnf t1)
            [(expr-Set a-ty)
             (if (check ctx s2 (expr-Set a-ty))
                 (tu (expr-Set a-ty) (add-usage u1 u2))
                 (tu-error))]
            [_ (tu-error)])]
         [(_ _) (tu-error)]))]
    ;; set-to-list: Set A → List A
    [(expr-set-to-list s)
     (let ([r (inferQ ctx s)])
       (match r
         [(tu _ u) (tu (infer ctx (expr-set-to-list s)) u)]
         [_ (tu-error)]))]

    ;; ---- PVec type and operations ----
    [(expr-PVec a)
     (let ([r (inferQ ctx a)])
       (match r
         [(tu _ u) (tu (expr-Type (lzero)) u)]
         [_ (tu-error)]))]
    [(expr-rrb _) (tu (expr-PVec (expr-hole)) (zero-usage n))]
    [(expr-pvec-empty a)
     (let ([r (inferQ ctx a)])
       (match r
         [(tu _ u) (tu (expr-PVec a) (scale-usage 'm0 u))]  ;; type arg is erased
         [_ (tu-error)]))]
    [(expr-pvec-push v x)
     (let ([r1 (inferQ ctx v)]
           [r2 (inferQ ctx x)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (tu-type r1) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-pvec-nth v i)
     (let ([r1 (inferQ ctx v)]
           [r2 (inferQ ctx i)])
       (match* (r1 r2)
         [((tu t1 u1) (tu _ u2))
          ;; pvec-nth returns the ELEMENT TYPE, not PVec
          (match t1
            [(expr-PVec a) (tu a (add-usage u1 u2))]
            [_ (tu-error)])]
         [(_ _) (tu-error)]))]
    [(expr-pvec-update v i x)
     (let ([r1 (inferQ ctx v)]
           [r2 (inferQ ctx i)]
           [r3 (inferQ ctx x)])
       (match* (r1 r2 r3)
         [((tu _ u1) (tu _ u2) (tu _ u3))
          (tu (tu-type r1) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]
    [(expr-pvec-length v)
     (let ([r (inferQ ctx v)])
       (match r
         [(tu _ u) (tu (expr-Nat) u)]
         [_ (tu-error)]))]
    [(expr-pvec-pop v)
     (let ([r (inferQ ctx v)])
       (match r
         [(tu _ u) (tu (tu-type r) u)]
         [_ (tu-error)]))]
    [(expr-pvec-concat v1 v2)
     (let ([r1 (inferQ ctx v1)]
           [r2 (inferQ ctx v2)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (tu-type r1) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-pvec-slice v lo hi)
     (let ([r1 (inferQ ctx v)]
           [r2 (inferQ ctx lo)]
           [r3 (inferQ ctx hi)])
       (match* (r1 r2 r3)
         [((tu _ u1) (tu _ u2) (tu _ u3))
          (tu (tu-type r1) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]
    ;; pvec-to-list : PVec A → List A
    [(expr-pvec-to-list v)
     (let ([r (inferQ ctx v)])
       (match r
         [(tu (expr-PVec a) u) (tu (expr-app (list-type-fvar) a) u)]
         [(tu _ u) (tu (tu-type r) u)]  ;; fallback if type not fully resolved
         [_ (tu-error)]))]
    ;; pvec-from-list : List A → PVec A
    ;; Infer the argument, match List A (qualified or unqualified), produce PVec A
    [(expr-pvec-from-list v)
     (let ([r (inferQ ctx v)])
       (match r
         [(tu _ u) (tu (infer ctx (expr-pvec-from-list v)) u)]
         [_ (tu-error)]))]

    ;; pvec-fold : (B → A → B) → B → PVec A → B
    ;; Uses checkQ for f when inferQ fails (e.g., f is a lambda).
    [(expr-pvec-fold f init vec)
     (let ([rv (inferQ ctx vec)]
           [ri (inferQ ctx init)])
       (match* (rv ri)
         [((tu tv uv) (tu tb ui))
          (match tv
            [(expr-PVec a)
             (let* ([ef (expr-Pi 'mw tb (expr-Pi 'mw (shift 1 0 a) (shift 2 0 tb)))]
                    [rf (inferQ-or-checkQ ctx f ef)])
               (match rf
                 [(tu _ uf) (tu tb (add-usage (add-usage uf ui) uv))]
                 [_ (tu-error)]))]
            [_ (tu-error)])]
         [(_ _) (tu-error)]))]

    ;; pvec-map : (A → B) → PVec A → PVec B
    [(expr-pvec-map f vec)
     (let ([result-type (infer ctx (expr-pvec-map f vec))]
           [rv (inferQ ctx vec)])
       (match rv
         [(tu tv uv)
          (match tv
            [(expr-PVec a)
             (let* ([rf (inferQ-or-checkQ ctx f (expr-Pi 'mw a (shift 1 0 result-type)))])
               (match rf
                 [(tu _ uf) (tu result-type (add-usage uf uv))]
                 [_ (tu-error)]))]
            [_ (tu-error)])]
         [_ (tu-error)]))]
    ;; pvec-filter : (A → Bool) → PVec A → PVec A
    [(expr-pvec-filter pred vec)
     (let ([rv (inferQ ctx vec)])
       (match rv
         [(tu tv uv)
          (match tv
            [(expr-PVec a)
             (let ([rp (inferQ-or-checkQ ctx pred (expr-Pi 'mw a (expr-Bool)))])
               (match rp
                 [(tu _ up) (tu (expr-PVec a) (add-usage up uv))]
                 [_ (tu-error)]))]
            [_ (tu-error)])]
         [_ (tu-error)]))]
    ;; set-fold : (B → A → B) → B → Set A → B
    [(expr-set-fold f init set)
     (let ([rs (inferQ ctx set)]
           [ri (inferQ ctx init)])
       (match* (rs ri)
         [((tu ts us) (tu tb ui))
          (match ts
            [(expr-Set a)
             (let* ([ef (expr-Pi 'mw tb (expr-Pi 'mw (shift 1 0 a) (shift 2 0 tb)))]
                    [rf (inferQ-or-checkQ ctx f ef)])
               (match rf
                 [(tu _ uf) (tu tb (add-usage (add-usage uf ui) us))]
                 [_ (tu-error)]))]
            [_ (tu-error)])]
         [(_ _) (tu-error)]))]
    ;; set-filter : (A → Bool) → Set A → Set A
    [(expr-set-filter pred set)
     (let ([rs (inferQ ctx set)])
       (match rs
         [(tu ts us)
          (match ts
            [(expr-Set a)
             (let ([rp (inferQ-or-checkQ ctx pred (expr-Pi 'mw a (expr-Bool)))])
               (match rp
                 [(tu _ up) (tu (expr-Set a) (add-usage up us))]
                 [_ (tu-error)]))]
            [_ (tu-error)])]
         [_ (tu-error)]))]
    ;; map-fold-entries : (B → K → V → B) → B → Map K V → B
    [(expr-map-fold-entries f init map)
     (let ([rm (inferQ ctx map)]
           [ri (inferQ ctx init)])
       (match* (rm ri)
         [((tu tm um) (tu tb ui))
          (match tm
            [(expr-Map k v)
             (let* ([ef (expr-Pi 'mw tb
                          (expr-Pi 'mw (shift 1 0 k)
                            (expr-Pi 'mw (shift 2 0 v) (shift 3 0 tb))))]
                    [rf (inferQ-or-checkQ ctx f ef)])
               (match rf
                 [(tu _ uf) (tu tb (add-usage (add-usage uf ui) um))]
                 [_ (tu-error)]))]
            [_ (tu-error)])]
         [(_ _) (tu-error)]))]
    ;; map-filter-entries : (K → V → Bool) → Map K V → Map K V
    [(expr-map-filter-entries pred map)
     (let ([rm (inferQ ctx map)])
       (match rm
         [(tu tm um)
          (match tm
            [(expr-Map k v)
             (let ([rp (inferQ-or-checkQ ctx pred
                         (expr-Pi 'mw k (expr-Pi 'mw (shift 1 0 v) (expr-Bool))))])
               (match rp
                 [(tu _ up) (tu (expr-Map k v) (add-usage up um))]
                 [_ (tu-error)]))]
            [_ (tu-error)])]
         [_ (tu-error)]))]
    ;; map-map-vals : (V → W) → Map K V → Map K W
    [(expr-map-map-vals f map)
     (let ([result-type (infer ctx (expr-map-map-vals f map))]
           [rm (inferQ ctx map)])
       (match rm
         [(tu tm um)
          (match tm
            [(expr-Map k v)
             (let ([rf (inferQ-or-checkQ ctx f (expr-Pi 'mw v (shift 1 0 result-type)))])
               (match rf
                 [(tu _ uf) (tu result-type (add-usage uf um))]
                 [_ (tu-error)]))]
            [_ (tu-error)])]
         [_ (tu-error)]))]

    ;; ---- Transient Builders ----
    ;; Generic transient/persist: dispatch on inferred type, combine usage
    [(expr-transient coll)
     (let ([r (inferQ ctx coll)])
       (match r
         [(tu tc u) (match tc
                      [(expr-PVec a) (tu (expr-TVec a) u)]
                      [(expr-Map k v) (tu (expr-TMap k v) u)]
                      [(expr-Set a) (tu (expr-TSet a) u)]
                      [_ (tu-error)])]
         [_ (tu-error)]))]
    [(expr-persist coll)
     (let ([r (inferQ ctx coll)])
       (match r
         [(tu tc u) (match tc
                      [(expr-TVec a) (tu (expr-PVec a) u)]
                      [(expr-TMap k v) (tu (expr-Map k v) u)]
                      [(expr-TSet a) (tu (expr-Set a) u)]
                      [_ (tu-error)])]
         [_ (tu-error)]))]
    ;; Panic: msg is runtime-relevant (mw), type is error (needs checking context)
    [(expr-panic msg)
     (let ([r (inferQ ctx msg)])
       (match r
         [(tu _ u) (tu (expr-error) u)]
         [_ (tu-error)]))]
    [(expr-TVec a)
     (let ([r (inferQ ctx a)])
       (match r
         [(tu _ u) (tu (expr-Type (lzero)) u)]
         [_ (tu-error)]))]
    [(expr-TMap k v)
     (let ([r1 (inferQ ctx k)]
           [r2 (inferQ ctx v)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (expr-Type (lzero)) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-TSet a)
     (let ([r (inferQ ctx a)])
       (match r
         [(tu _ u) (tu (expr-Type (lzero)) u)]
         [_ (tu-error)]))]
    [(expr-trrb _) (tu (expr-TVec (expr-hole)) (zero-usage n))]
    [(expr-tchamp _) (tu (expr-TMap (expr-hole) (expr-hole)) (zero-usage n))]
    [(expr-thset _) (tu (expr-TSet (expr-hole)) (zero-usage n))]
    [(expr-transient-vec v)
     (let ([r (inferQ ctx v)])
       (match r
         [(tu tv u) (match tv
                      [(expr-PVec a) (tu (expr-TVec a) u)]
                      [_ (tu-error)])]
         [_ (tu-error)]))]
    [(expr-persist-vec t)
     (let ([r (inferQ ctx t)])
       (match r
         [(tu tt u) (match tt
                      [(expr-TVec a) (tu (expr-PVec a) u)]
                      [_ (tu-error)])]
         [_ (tu-error)]))]
    [(expr-transient-map m)
     (let ([r (inferQ ctx m)])
       (match r
         [(tu tm u) (match tm
                      [(expr-Map k v) (tu (expr-TMap k v) u)]
                      [_ (tu-error)])]
         [_ (tu-error)]))]
    [(expr-persist-map t)
     (let ([r (inferQ ctx t)])
       (match r
         [(tu tt u) (match tt
                      [(expr-TMap k v) (tu (expr-Map k v) u)]
                      [_ (tu-error)])]
         [_ (tu-error)]))]
    [(expr-transient-set s)
     (let ([r (inferQ ctx s)])
       (match r
         [(tu ts u) (match ts
                      [(expr-Set a) (tu (expr-TSet a) u)]
                      [_ (tu-error)])]
         [_ (tu-error)]))]
    [(expr-persist-set t)
     (let ([r (inferQ ctx t)])
       (match r
         [(tu tt u) (match tt
                      [(expr-TSet a) (tu (expr-Set a) u)]
                      [_ (tu-error)])]
         [_ (tu-error)]))]
    [(expr-tvec-push! t x)
     (let ([r1 (inferQ ctx t)]
           [r2 (inferQ ctx x)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (tu-type r1) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-tvec-update! t i x)
     (let ([r1 (inferQ ctx t)]
           [r2 (inferQ ctx i)]
           [r3 (inferQ ctx x)])
       (match* (r1 r2 r3)
         [((tu _ u1) (tu _ u2) (tu _ u3))
          (tu (tu-type r1) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]
    [(expr-tmap-assoc! t k v)
     (let ([r1 (inferQ ctx t)]
           [r2 (inferQ ctx k)]
           [r3 (inferQ ctx v)])
       (match* (r1 r2 r3)
         [((tu _ u1) (tu _ u2) (tu _ u3))
          (tu (tu-type r1) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]
    [(expr-tmap-dissoc! t k)
     (let ([r1 (inferQ ctx t)]
           [r2 (inferQ ctx k)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (tu-type r1) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-tset-insert! t a)
     (let ([r1 (inferQ ctx t)]
           [r2 (inferQ ctx a)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (tu-type r1) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-tset-delete! t a)
     (let ([r1 (inferQ ctx t)]
           [r2 (inferQ ctx a)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (tu-type r1) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; ---- PropNetwork type constructors ----
    [(expr-net-type) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-cell-id-type) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-prop-id-type) (tu (expr-Type (lzero)) (zero-usage n))]
    ;; Runtime wrappers — zero usage (opaque Racket values)
    [(expr-prop-network _) (tu (expr-net-type) (zero-usage n))]
    [(expr-cell-id _) (tu (expr-cell-id-type) (zero-usage n))]
    [(expr-prop-id _) (tu (expr-prop-id-type) (zero-usage n))]

    ;; ---- PropNetwork operations ----
    ;; net-new : Int -> PropNetwork
    [(expr-net-new fuel)
     (let ([r1 (checkQ ctx fuel (expr-Int))])
       (match r1
         [(bu #t u) (tu (expr-net-type) u)]
         [_ (tu-error)]))]

    ;; net-new-cell : PropNetwork -> A -> (A -> A -> A) -> [PropNetwork * CellId]
    ;; Use checkQ for merge (not inferQ) because inferQ can't handle standalone lambdas.
    ;; The merge type A -> A -> A is computed from init's inferred type, with proper
    ;; de Bruijn shifts under Pi binders (init-ty may contain bvars in polymorphic contexts).
    [(expr-net-new-cell net init merge)
     (let ([r1 (inferQ ctx net)]
           [r2 (inferQ ctx init)])
       (match* (r1 r2)
         [((tu _ u1) (tu init-ty u2))
          ;; Build merge type: A -> A -> A with proper shifts under Pi binders
          (define merge-ty (expr-Pi mw init-ty
                             (expr-Pi mw (shift 1 0 init-ty)
                               (shift 2 0 init-ty))))
          (let ([r3 (checkQ ctx merge merge-ty)])
            (match r3
              [(bu #t u3)
               (tu (expr-Sigma (expr-net-type) (expr-cell-id-type))
                   (add-usage u1 (add-usage u2 u3)))]
              [_ (tu-error)]))]
         [(_ _) (tu-error)]))]

    ;; net-new-cell-widen : PropNetwork -> A -> (A A -> A) -> (A A -> A) -> (A A -> A) -> [PropNetwork * CellId]
    ;; Use checkQ for all function args (merge, widen, narrow) since inferQ can't handle standalone lambdas.
    [(expr-net-new-cell-widen net init merge widen-fn narrow-fn)
     (let ([r1 (inferQ ctx net)]
           [r2 (inferQ ctx init)])
       (match* (r1 r2)
         [((tu _ u1) (tu init-ty u2))
          (define fn-ty (expr-Pi mw init-ty
                          (expr-Pi mw (shift 1 0 init-ty)
                            (shift 2 0 init-ty))))
          (let ([r3 (checkQ ctx merge fn-ty)]
                [r4 (checkQ ctx widen-fn fn-ty)]
                [r5 (checkQ ctx narrow-fn fn-ty)])
            (match* (r3 r4 r5)
              [((bu #t u3) (bu #t u4) (bu #t u5))
               (tu (expr-Sigma (expr-net-type) (expr-cell-id-type))
                   (add-usage u1 (add-usage u2 (add-usage u3 (add-usage u4 u5)))))]
              [(_ _ _) (tu-error)]))]
         [(_ _) (tu-error)]))]

    ;; net-cell-read : PropNetwork -> CellId -> A
    [(expr-net-cell-read net cell)
     (let ([r1 (inferQ ctx net)]
           [r2 (inferQ ctx cell)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (infer ctx e) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; net-cell-write : PropNetwork -> CellId -> A -> PropNetwork
    [(expr-net-cell-write net cell val)
     (let ([r1 (inferQ ctx net)]
           [r2 (inferQ ctx cell)]
           [r3 (inferQ ctx val)])
       (match* (r1 r2 r3)
         [((tu _ u1) (tu _ u2) (tu _ u3))
          (tu (expr-net-type) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]

    ;; net-add-prop : PropNetwork -> [List CellId] -> [List CellId] -> fn -> [PropNetwork * PropId]
    [(expr-net-add-prop net ins outs fn)
     (let ([r1 (inferQ ctx net)]
           [r2 (inferQ ctx ins)]
           [r3 (inferQ ctx outs)]
           [r4 (inferQ ctx fn)])
       (match* (r1 r2 r3 r4)
         [((tu _ u1) (tu _ u2) (tu _ u3) (tu _ u4))
          (tu (expr-Sigma (expr-net-type) (expr-prop-id-type))
              (add-usage u1 (add-usage u2 (add-usage u3 u4))))]
         [(_ _ _ _) (tu-error)]))]

    ;; net-run : PropNetwork -> PropNetwork
    [(expr-net-run net)
     (let ([r1 (inferQ ctx net)])
       (match r1
         [(tu _ u) (tu (expr-net-type) u)]
         [_ (tu-error)]))]

    ;; net-snapshot : PropNetwork -> PropNetwork
    [(expr-net-snapshot net)
     (let ([r1 (inferQ ctx net)])
       (match r1
         [(tu _ u) (tu (expr-net-type) u)]
         [_ (tu-error)]))]

    ;; net-contradict? : PropNetwork -> Bool
    [(expr-net-contradiction net)
     (let ([r1 (inferQ ctx net)])
       (match r1
         [(tu _ u) (tu (expr-Bool) u)]
         [_ (tu-error)]))]

    ;; ---- UnionFind type constructor ----
    [(expr-uf-type) (tu (expr-Type (lzero)) (zero-usage n))]
    ;; Runtime wrapper
    [(expr-uf-store _) (tu (expr-uf-type) (zero-usage n))]

    ;; ---- UnionFind operations ----

    ;; uf-empty : UnionFind
    [(expr-uf-empty) (tu (expr-uf-type) (zero-usage n))]

    ;; uf-make-set : UnionFind -> Nat -> A -> UnionFind
    [(expr-uf-make-set store id val)
     (let ([r1 (inferQ ctx store)]
           [r2 (inferQ ctx id)]
           [r3 (inferQ ctx val)])
       (match* (r1 r2 r3)
         [((tu _ u1) (tu _ u2) (tu _ u3))
          (tu (expr-uf-type) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]

    ;; uf-find : UnionFind -> Nat -> [Nat * UnionFind]
    [(expr-uf-find store id)
     (let ([r1 (inferQ ctx store)]
           [r2 (inferQ ctx id)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (expr-Sigma (expr-Nat) (expr-uf-type)) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; uf-union : UnionFind -> Nat -> Nat -> UnionFind
    [(expr-uf-union store id1 id2)
     (let ([r1 (inferQ ctx store)]
           [r2 (inferQ ctx id1)]
           [r3 (inferQ ctx id2)])
       (match* (r1 r2 r3)
         [((tu _ u1) (tu _ u2) (tu _ u3))
          (tu (expr-uf-type) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]

    ;; uf-value : UnionFind -> Nat -> A (type-unsafe)
    [(expr-uf-value store id)
     (let ([r1 (inferQ ctx store)]
           [r2 (inferQ ctx id)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (infer ctx e) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; ---- ATMS type constructors ----
    [(expr-atms-type) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-assumption-id-type) (tu (expr-Type (lzero)) (zero-usage n))]
    ;; Runtime wrappers
    [(expr-atms-store _) (tu (expr-atms-type) (zero-usage n))]
    [(expr-assumption-id-val _) (tu (expr-assumption-id-type) (zero-usage n))]

    ;; ---- ATMS operations ----

    ;; atms-new : PropNetwork -> ATMS
    [(expr-atms-new net)
     (let ([r1 (inferQ ctx net)])
       (match r1
         [(tu _ u) (tu (expr-atms-type) u)]
         [_ (tu-error)]))]

    ;; atms-assume : ATMS -> A -> A -> [ATMS * AssumptionId]
    [(expr-atms-assume a nm d)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx nm)]
           [r3 (inferQ ctx d)])
       (match* (r1 r2 r3)
         [((tu _ u1) (tu _ u2) (tu _ u3))
          (tu (infer ctx e) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]

    ;; atms-retract : ATMS -> AssumptionId -> ATMS
    [(expr-atms-retract a aid)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx aid)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (expr-atms-type) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; atms-nogood : ATMS -> List AssumptionId -> ATMS
    [(expr-atms-nogood a aids)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx aids)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (expr-atms-type) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; atms-amb : ATMS -> List A -> [ATMS * _]
    [(expr-atms-amb a alts)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx alts)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (infer ctx e) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; atms-solve-all : ATMS -> CellId -> _
    [(expr-atms-solve-all a g)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx g)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (infer ctx e) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; atms-read : ATMS -> CellId -> _
    [(expr-atms-read a c)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx c)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (infer ctx e) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; atms-write : ATMS -> CellId -> A -> List AssumptionId -> ATMS
    [(expr-atms-write a c v s)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx c)]
           [r3 (inferQ ctx v)]
           [r4 (inferQ ctx s)])
       (match* (r1 r2 r3 r4)
         [((tu _ u1) (tu _ u2) (tu _ u3) (tu _ u4))
          (tu (expr-atms-type) (add-usage u1 (add-usage u2 (add-usage u3 u4))))]
         [(_ _ _ _) (tu-error)]))]

    ;; atms-consistent? : ATMS -> List AssumptionId -> Bool
    [(expr-atms-consistent a aids)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx aids)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; atms-worldview : ATMS -> List AssumptionId -> ATMS
    [(expr-atms-worldview a aids)
     (let ([r1 (inferQ ctx a)]
           [r2 (inferQ ctx aids)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (expr-atms-type) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; ---- Tabling type constructor + wrapper ----
    [(expr-table-store-type) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-table-store-val _) (tu (expr-table-store-type) (zero-usage n))]

    ;; ---- Tabling operations ----

    ;; table-new : PropNetwork -> TableStore
    [(expr-table-new net)
     (let ([r1 (inferQ ctx net)])
       (match r1
         [(tu _ u) (tu (expr-table-store-type) u)]
         [_ (tu-error)]))]

    ;; table-register : TableStore -> Keyword -> Keyword -> [TableStore * CellId]
    [(expr-table-register s n m)
     (let ([r1 (inferQ ctx s)]
           [r2 (inferQ ctx n)]
           [r3 (inferQ ctx m)])
       (match* (r1 r2 r3)
         [((tu _ u1) (tu _ u2) (tu _ u3))
          (tu (infer ctx e) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]

    ;; table-add : TableStore -> Keyword -> A -> TableStore
    [(expr-table-add s n a)
     (let ([r1 (inferQ ctx s)]
           [r2 (inferQ ctx n)]
           [r3 (inferQ ctx a)])
       (match* (r1 r2 r3)
         [((tu _ u1) (tu _ u2) (tu _ u3))
          (tu (expr-table-store-type) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]

    ;; table-answers : TableStore -> Keyword -> _ (type-unsafe)
    [(expr-table-answers s n)
     (let ([r1 (inferQ ctx s)]
           [r2 (inferQ ctx n)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (infer ctx e) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; table-freeze : TableStore -> Keyword -> TableStore
    [(expr-table-freeze s n)
     (let ([r1 (inferQ ctx s)]
           [r2 (inferQ ctx n)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (expr-table-store-type) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; table-complete? : TableStore -> Keyword -> Bool
    [(expr-table-complete s n)
     (let ([r1 (inferQ ctx s)]
           [r2 (inferQ ctx n)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (tu (expr-Bool) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]

    ;; table-run : TableStore -> TableStore
    [(expr-table-run s)
     (let ([r1 (inferQ ctx s)])
       (match r1
         [(tu _ u) (tu (expr-table-store-type) u)]
         [_ (tu-error)]))]

    ;; table-lookup : TableStore -> Keyword -> A -> Bool
    [(expr-table-lookup s n a)
     (let ([r1 (inferQ ctx s)]
           [r2 (inferQ ctx n)]
           [r3 (inferQ ctx a)])
       (match* (r1 r2 r3)
         [((tu _ u1) (tu _ u2) (tu _ u3))
          (tu (expr-Bool) (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (tu-error)]))]

    ;; ---- Relational language (Phase 7) ----
    ;; Type constructors → zero usage
    [(expr-solver-type) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-goal-type) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-derivation-type) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-cut) (tu (expr-goal-type) (zero-usage n))]
    [(expr-schema-type _) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-answer-type t)
     (if t
         (let ([r (inferQ ctx t)])
           (match r
             [(tu _ u) (tu (expr-Type (lzero)) u)]
             [_ (tu-error)]))
         (tu (expr-Type (lzero)) (zero-usage n)))]
    [(expr-relation-type pts)
     (let ([rs (map (lambda (p) (inferQ ctx p)) pts)])
       (define usages (for/list ([r (in-list rs)])
                        (match r [(tu _ u) u] [_ (zero-usage n)])))
       (tu (expr-Type (lzero)) (foldl add-usage (zero-usage n) usages)))]
    [(expr-solver-config _) (tu (expr-solver-type) (zero-usage n))]
    [(expr-logic-var _ _) (tu (expr-hole) (zero-usage n))]
    ;; Compound relational nodes — sum sub-expression usages
    [(expr-defr nm sc vs)
     (define su (if sc (match (inferQ ctx sc) [(tu _ u) u] [_ (zero-usage n)]) (zero-usage n)))
     (define vus (for/list ([v (in-list vs)])
                   (match (inferQ ctx v) [(tu _ u) u] [_ (zero-usage n)])))
     (tu (expr-hole) (foldl add-usage su vus))]
    [(expr-defr-variant ps bd)
     (define us (map (lambda (b) (inferQ ctx b)) bd))
     (define usages (map (lambda (r) (match r [(tu _ u) u] [_ '()])) us))
     (tu (expr-hole) (foldl add-usage (zero-usage n) usages))]
    [(expr-rel ps cls)
     (define cus (for/list ([c (in-list cls)])
                   (match (inferQ ctx c) [(tu _ u) u] [_ (zero-usage n)])))
     (tu (expr-hole) (foldl add-usage (zero-usage n) cus))]
    [(expr-clause gs)
     (define gus (for/list ([g (in-list gs)])
                   (match (inferQ ctx g) [(tu _ u) u] [_ (zero-usage n)])))
     (tu (expr-goal-type) (foldl add-usage (zero-usage n) gus))]
    [(expr-fact-block rs)
     (define rus (for/list ([r (in-list rs)])
                   (match (inferQ ctx r) [(tu _ u) u] [_ (zero-usage n)])))
     (tu (expr-goal-type) (foldl add-usage (zero-usage n) rus))]
    [(expr-fact-row ts)
     (define tus (for/list ([t (in-list ts)])
                   (match (inferQ ctx t) [(tu _ u) u] [_ (zero-usage n)])))
     (tu (expr-hole) (foldl add-usage (zero-usage n) tus))]
    [(expr-goal-app nm as)
     (let ([rn (inferQ ctx nm)])
       (define nus (for/list ([a (in-list as)])
                     (match (inferQ ctx a) [(tu _ u) u] [_ (zero-usage n)])))
       (match rn
         [(tu _ u0) (tu (expr-goal-type) (foldl add-usage u0 nus))]
         [_ (tu-error)]))]
    [(expr-unify-goal l r)
     (let ([r1 (inferQ ctx l)] [r2 (inferQ ctx r)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2)) (tu (expr-goal-type) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-is-goal v ex)
     (let ([r1 (inferQ ctx v)] [r2 (inferQ ctx ex)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2)) (tu (expr-goal-type) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-not-goal g)
     (let ([r (inferQ ctx g)])
       (match r [(tu _ u) (tu (expr-goal-type) u)] [_ (tu-error)]))]
    [(expr-guard cond goal)
     (let ([r1 (inferQ ctx cond)] [r2 (inferQ ctx goal)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2)) (tu (expr-goal-type) (add-usage u1 u2))]
         [(_ _) (tu-error)]))]
    [(expr-schema nm fs)
     (define fus (for/list ([f (in-list fs)])
                   (match (inferQ ctx f) [(tu _ u) u] [_ (zero-usage n)])))
     (tu (expr-schema-type nm) (foldl add-usage (zero-usage n) fus))]
    [(expr-solve g)
     (let ([r (inferQ ctx g)])
       (match r [(tu _ u) (tu (expr-hole) u)] [_ (tu-error)]))]
    [(expr-solve-with sv ov g)
     (define su (if sv (match (inferQ ctx sv) [(tu _ u) u] [_ (zero-usage n)]) (zero-usage n)))
     (define ou (if ov (match (inferQ ctx ov) [(tu _ u) u] [_ (zero-usage n)]) (zero-usage n)))
     (let ([rg (inferQ ctx g)])
       (match rg
         [(tu _ ug) (tu (expr-hole) (add-usage su (add-usage ou ug)))]
         [_ (tu-error)]))]
    [(expr-solve-one g)
     (let ([r (inferQ ctx g)])
       (match r [(tu _ u) (tu (expr-hole) u)] [_ (tu-error)]))]
    [(expr-explain g)
     (let ([r (inferQ ctx g)])
       (match r [(tu _ u) (tu (expr-hole) u)] [_ (tu-error)]))]
    [(expr-explain-with sv ov g)
     (define su (if sv (match (inferQ ctx sv) [(tu _ u) u] [_ (zero-usage n)]) (zero-usage n)))
     (define ou (if ov (match (inferQ ctx ov) [(tu _ u) u] [_ (zero-usage n)]) (zero-usage n)))
     (let ([rg (inferQ ctx g)])
       (match rg
         [(tu _ ug) (tu (expr-hole) (add-usage su (add-usage ou ug)))]
         [_ (tu-error)]))]

    ;; ---- J eliminator ----
    ;; Usage from proof, base, motive arguments
    [(expr-J mot base left right proof)
     (let ([r5 (inferQ ctx proof)])
       (match r5
         [(tu t5 u5)
          (match (whnf t5)
            [(expr-Eq t t1 t2)
             (if (and (unify-ok? (unify ctx t1 left))
                      (unify-ok? (unify ctx t2 right))
                      ;; Verify base type: Π(a:A). motive(a, a, refl)
                      (check ctx base
                        (expr-Pi 'mw t
                          (expr-app (expr-app (expr-app (shift 1 0 mot) (expr-bvar 0))
                                              (expr-bvar 0))
                                    (expr-refl)))))
                 (tu (expr-app (expr-app (expr-app mot left) right) proof) u5)
                 (tu-error))]
            [_ (tu-error)])]
         [_ (tu-error)]))]

    ;; ---- Vec/Fin type constructors: zero usage for types ----
    [(expr-Vec _ _) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-Fin _) (tu (expr-Type (lzero)) (zero-usage n))]

    ;; ---- Fallback ----
    [_ (tu-error)]))

;; ========================================
;; QTT checking: checkQ(ctx, e, T) -> BoolUsage
;; ========================================
(define (checkQ ctx e t)
  (define n (ctx-len ctx))
  (define t-whnf (whnf t))
  (match* (e t-whnf)
    ;; ---- suc: check against Nat ----
    [((expr-suc e1) (expr-Nat))
     (let ([r (checkQ ctx e1 (expr-Nat))])
       (match r
         [(bu #t u) (bu #t u)]
         [_ (bu #f (zero-usage n))]))]
    ;; ---- nat-val: always Nat, zero usage ----
    [((expr-nat-val _) (expr-Nat)) (bu #t (zero-usage n))]

    ;; ---- Panic: inhabits any type, count msg usage ----
    [((expr-panic msg) _)
     (let ([r (checkQ ctx msg (expr-String))])
       (match r
         [(bu #t u) (bu #t u)]
         [_ (bu #f (zero-usage n))]))]

    ;; ---- Lambda: check against Pi ----
    ;; Sprint 7: mult-meta-aware — resolve mult-metas from Pi context or usage
    [((expr-lam m a body) (expr-Pi m2 t-dom b))
     (let* ([effective-m (cond
                           [(mult-meta? m) (if (mult-meta? m2) 'mw m2)]
                           [(mult-meta? m2) m]
                           [else m])]
            [mults-ok (or (mult-meta? m) (mult-meta? m2) (eq? m m2))])
       (cond
         [(not mults-ok)
          (bu #f (zero-usage n))]
         [(and (not (expr-hole? a)) (not (unify-ok? (unify ctx a t-dom))))
          (bu #f (zero-usage n))]
         [else
          ;; Use Pi domain when lambda domain is a hole (mirrors type checker behavior)
          (define ctx-dom (if (expr-hole? a) t-dom a))
          (let ([r (checkQ (ctx-extend ctx ctx-dom effective-m) body b)])
            (match r
              [(bu #t u)
               (let ([actual-usage (uhead u)])
                 ;; Sprint 7: solve mult-metas to observed usage
                 (when (and (mult-meta? m) (not (mult-meta-solved? (mult-meta-id m))))
                   (solve-mult-meta! (mult-meta-id m) actual-usage))
                 (when (and (mult-meta? m2) (not (mult-meta-solved? (mult-meta-id m2))))
                   (solve-mult-meta! (mult-meta-id m2) actual-usage))
                 (if (compatible effective-m actual-usage)
                     (bu #t (utail u))
                     (bu #f (zero-usage n))))]
              [_ (bu #f (zero-usage n))]))]))]

    ;; ---- Pair: check against Sigma ----
    [((expr-pair e1 e2) (expr-Sigma a b))
     (let ([r1 (checkQ ctx e1 a)])
       (match r1
         [(bu #t u1)
          (let ([r2 (checkQ ctx e2 (subst 0 e1 b))])
            (match r2
              [(bu #t u2) (bu #t (add-usage u1 u2))]
              [_ (bu #f (zero-usage n))]))]
         [_ (bu #f (zero-usage n))]))]

    ;; ---- refl: check against Eq ----
    [((expr-refl) (expr-Eq _ e1 e2))
     (bu (unify-ok? (unify ctx e1 e2)) (zero-usage n))]

    ;; ---- Holes: optimistically succeed with zero usage ----
    ;; Holes (_, ??name) don't consume resources — mirrors typing-core check behavior.
    [((expr-hole) _) (bu #t (zero-usage n))]
    [((expr-typed-hole _) _) (bu #t (zero-usage n))]

    ;; ---- Meta expression: optimistically succeed with zero usage ----
    ;; A metavariable (from implicit arg insertion) doesn't consume resources.
    [((expr-meta _) _) (bu #t (zero-usage n))]

    ;; ---- Symbol literal: check against Symbol type ----
    [((expr-symbol _) (expr-Symbol)) (bu #t (zero-usage n))]

    ;; ---- Keyword literal: check against Keyword type ----
    [((expr-keyword _) (expr-Keyword)) (bu #t (zero-usage n))]

    ;; ---- Char literal: check against Char type ----
    [((expr-char _) (expr-Char)) (bu #t (zero-usage n))]

    ;; ---- String literal: check against String type ----
    [((expr-string _) (expr-String)) (bu #t (zero-usage n))]

    ;; ---- Map constructors: check against Map type ----
    [((expr-champ _) (expr-Map _ _)) (bu #t (zero-usage n))]
    [((expr-map-empty k v) (expr-Map _ _))
     (let ([r1 (inferQ ctx k)]
           [r2 (inferQ ctx v)])
       (match* (r1 r2)
         [((tu _ u1) (tu _ u2))
          (bu #t (scale-usage 'm0 (add-usage u1 u2)))]  ;; type args are erased
         [(_ _) (bu #f (zero-usage n))]))]
    ;; map-assoc checked against Map K V — propagate expected type
    [((expr-map-assoc m k v) (expr-Map kt vt))
     (let ([rm (checkQ ctx m (expr-Map kt vt))]
           [rk (checkQ ctx k kt)]
           [rv (checkQ ctx v vt)])
       (match* (rm rk rv)
         [((bu #t u1) (bu #t u2) (bu #t u3))
          (bu #t (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (bu #f (zero-usage n))]))]

    ;; ---- Map constructors: check against Schema type (fvar) ----
    ;; Schema types are opaque fvar types backed by maps; QTT tracks usage normally.
    [((expr-champ _) (expr-fvar name))
     #:when (lookup-schema-by-name name)
     (bu #t (zero-usage n))]
    [((expr-map-empty _ _) (expr-fvar name))
     #:when (lookup-schema-by-name name)
     ;; Type args of map-empty are erased (m0) — zero usage, same as (expr-champ)
     (bu #t (zero-usage n))]
    [((expr-map-assoc m k v) (expr-fvar name))
     #:when (lookup-schema-by-name name)
     ;; Check submap against same schema type; infer key/value usage
     (let ([rm (checkQ ctx m (expr-fvar name))]
           [rk (inferQ ctx k)]
           [rv (inferQ ctx v)])
       (match* (rm rk rv)
         [((bu #t u1) (tu _ u2) (tu _ u3))
          (bu #t (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (bu #f (zero-usage n))]))]
    ;; ---- Map constructors: check against Selection type (fvar) ----
    ;; Selection types delegate to parent schema at value level.
    [((expr-champ _) (expr-fvar name))
     #:when (lookup-selection-by-name name)
     (bu #t (zero-usage n))]
    [((expr-map-empty _ _) (expr-fvar name))
     #:when (lookup-selection-by-name name)
     (bu #t (zero-usage n))]
    [((expr-map-assoc m k v) (expr-fvar name))
     #:when (lookup-selection-by-name name)
     ;; Selection types delegate to parent schema at value level for QTT.
     (let ([rm (checkQ ctx m (expr-fvar name))]
           [rk (inferQ ctx k)]
           [rv (inferQ ctx v)])
       (match* (rm rk rv)
         [((bu #t u1) (tu _ u2) (tu _ u3))
          (bu #t (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (bu #f (zero-usage n))]))]

    ;; ---- Set constructors: check against Set type ----
    [((expr-hset _) (expr-Set _)) (bu #t (zero-usage n))]
    [((expr-set-empty a) (expr-Set _))
     (let ([r (inferQ ctx a)])
       (match r
         [(tu _ u) (bu #t (scale-usage 'm0 u))]  ;; type arg is erased
         [_ (bu #f (zero-usage n))]))]
    [((expr-set-insert s a) (expr-Set a-ty))
     (let ([rs (checkQ ctx s (expr-Set a-ty))]
           [ra (checkQ ctx a a-ty)])
       (match* (rs ra)
         [((bu #t u1) (bu #t u2))
          (bu #t (add-usage u1 u2))]
         [(_ _) (bu #f (zero-usage n))]))]

    ;; ---- PVec constructors: check against PVec type ----
    [((expr-rrb _) (expr-PVec _)) (bu #t (zero-usage n))]
    [((expr-pvec-empty a) (expr-PVec _))
     (let ([r (inferQ ctx a)])
       (match r
         [(tu _ u) (bu #t (scale-usage 'm0 u))]  ;; type arg is erased
         [_ (bu #f (zero-usage n))]))]
    [((expr-pvec-push v x) (expr-PVec a))
     (let ([rv (checkQ ctx v (expr-PVec a))]
           [rx (checkQ ctx x a)])
       (match* (rv rx)
         [((bu #t u1) (bu #t u2))
          (bu #t (add-usage u1 u2))]
         [(_ _) (bu #f (zero-usage n))]))]
    ;; pvec-fold : check f, init, vec — result type is expected-type
    [((expr-pvec-fold f init vec) expected-type)
     (let ([rv (inferQ ctx vec)]
           [ri (checkQ ctx init expected-type)])
       (match* (rv ri)
         [((tu tv uv) (bu #t ui))
          (match tv
            [(expr-PVec a)
             (let* ([ef (expr-Pi 'mw expected-type
                          (expr-Pi 'mw (shift 1 0 a) (shift 2 0 expected-type)))]
                    [rf (inferQ-or-checkQ ctx f ef)])
               (match rf
                 [(tu _ uf) (bu #t (add-usage (add-usage uf ui) uv))]
                 [_ (bu #f (zero-usage n))]))]
            [_ (bu #f (zero-usage n))])]
         [(_ _) (bu #f (zero-usage n))]))]
    ;; pvec-map : check against PVec B
    [((expr-pvec-map f vec) expected-type)
     (let ([rv (inferQ ctx vec)])
       (match rv
         [(tu tv uv)
          (match* (tv (whnf expected-type))
            [((expr-PVec a) (expr-PVec b))
             (let ([rf (inferQ-or-checkQ ctx f (expr-Pi 'mw a (shift 1 0 b)))])
               (match rf
                 [(tu _ uf)
                  (bu (check ctx (expr-pvec-map f vec) expected-type)
                      (add-usage uf uv))]
                 [_ (bu #f (zero-usage n))]))]
            [(_ _) (bu #f (zero-usage n))])]
         [_ (bu #f (zero-usage n))]))]
    ;; pvec-filter : check against PVec A
    [((expr-pvec-filter pred vec) expected-type)
     (let ([rv (inferQ ctx vec)])
       (match rv
         [(tu tv uv)
          (match tv
            [(expr-PVec a)
             (let ([rp (inferQ-or-checkQ ctx pred (expr-Pi 'mw a (expr-Bool)))])
               (match rp
                 [(tu _ up)
                  (bu (check ctx (expr-pvec-filter pred vec) expected-type)
                      (add-usage up uv))]
                 [_ (bu #f (zero-usage n))]))]
            [_ (bu #f (zero-usage n))])]
         [_ (bu #f (zero-usage n))]))]
    ;; set-fold : check
    [((expr-set-fold f init set) expected-type)
     (let ([rs (inferQ ctx set)]
           [ri (checkQ ctx init expected-type)])
       (match* (rs ri)
         [((tu ts us) (bu #t ui))
          (match ts
            [(expr-Set a)
             (let* ([ef (expr-Pi 'mw expected-type
                          (expr-Pi 'mw (shift 1 0 a) (shift 2 0 expected-type)))]
                    [rf (inferQ-or-checkQ ctx f ef)])
               (match rf
                 [(tu _ uf) (bu #t (add-usage (add-usage uf ui) us))]
                 [_ (bu #f (zero-usage n))]))]
            [_ (bu #f (zero-usage n))])]
         [(_ _) (bu #f (zero-usage n))]))]
    ;; set-filter : check against Set A
    [((expr-set-filter pred set) expected-type)
     (let ([rs (inferQ ctx set)])
       (match rs
         [(tu ts us)
          (match ts
            [(expr-Set a)
             (let ([rp (inferQ-or-checkQ ctx pred (expr-Pi 'mw a (expr-Bool)))])
               (match rp
                 [(tu _ up)
                  (bu (check ctx (expr-set-filter pred set) expected-type)
                      (add-usage up us))]
                 [_ (bu #f (zero-usage n))]))]
            [_ (bu #f (zero-usage n))])]
         [_ (bu #f (zero-usage n))]))]
    ;; map-fold-entries : check
    [((expr-map-fold-entries f init map) expected-type)
     (let ([rm (inferQ ctx map)]
           [ri (checkQ ctx init expected-type)])
       (match* (rm ri)
         [((tu tm um) (bu #t ui))
          (match tm
            [(expr-Map k v)
             (let* ([ef (expr-Pi 'mw expected-type
                          (expr-Pi 'mw (shift 1 0 k)
                            (expr-Pi 'mw (shift 2 0 v) (shift 3 0 expected-type))))]
                    [rf (inferQ-or-checkQ ctx f ef)])
               (match rf
                 [(tu _ uf) (bu #t (add-usage (add-usage uf ui) um))]
                 [_ (bu #f (zero-usage n))]))]
            [_ (bu #f (zero-usage n))])]
         [(_ _) (bu #f (zero-usage n))]))]
    ;; map-filter-entries : check against Map K V
    [((expr-map-filter-entries pred map) expected-type)
     (let ([rm (inferQ ctx map)])
       (match rm
         [(tu tm um)
          (match tm
            [(expr-Map k v)
             (let ([rp (inferQ-or-checkQ ctx pred
                         (expr-Pi 'mw k (expr-Pi 'mw (shift 1 0 v) (expr-Bool))))])
               (match rp
                 [(tu _ up)
                  (bu (check ctx (expr-map-filter-entries pred map) expected-type)
                      (add-usage up um))]
                 [_ (bu #f (zero-usage n))]))]
            [_ (bu #f (zero-usage n))])]
         [_ (bu #f (zero-usage n))]))]
    ;; map-map-vals : check against Map K W
    [((expr-map-map-vals f map) expected-type)
     (let ([rm (inferQ ctx map)])
       (match rm
         [(tu tm um)
          (match* (tm (whnf expected-type))
            [((expr-Map k2 v) (expr-Map k w))
             (let ([rf (inferQ-or-checkQ ctx f (expr-Pi 'mw v (shift 1 0 w)))])
               (match rf
                 [(tu _ uf)
                  (bu (and (unify-ok? (unify ctx k k2))
                           (check ctx (expr-map-map-vals f map) expected-type))
                      (add-usage uf um))]
                 [_ (bu #f (zero-usage n))]))]
            [(_ _) (bu #f (zero-usage n))])]
         [_ (bu #f (zero-usage n))]))]

    ;; ---- Transient Builder constructors: check against transient types ----
    [((expr-trrb _) (expr-TVec _)) (bu #t (zero-usage n))]
    [((expr-tchamp _) (expr-TMap _ _)) (bu #t (zero-usage n))]
    [((expr-thset _) (expr-TSet _)) (bu #t (zero-usage n))]
    [((expr-persist-vec t) (expr-PVec a))
     (let ([r (checkQ ctx t (expr-TVec a))])
       (match r
         [(bu #t u) (bu #t u)]
         [_ (bu #f (zero-usage n))]))]
    [((expr-persist-map t) (expr-Map k v))
     (let ([r (checkQ ctx t (expr-TMap k v))])
       (match r
         [(bu #t u) (bu #t u)]
         [_ (bu #f (zero-usage n))]))]
    [((expr-persist-set t) (expr-Set a))
     (let ([r (checkQ ctx t (expr-TSet a))])
       (match r
         [(bu #t u) (bu #t u)]
         [_ (bu #f (zero-usage n))]))]
    [((expr-tvec-push! t x) (expr-TVec a))
     (let ([rt (checkQ ctx t (expr-TVec a))]
           [rx (checkQ ctx x a)])
       (match* (rt rx)
         [((bu #t u1) (bu #t u2))
          (bu #t (add-usage u1 u2))]
         [(_ _) (bu #f (zero-usage n))]))]
    [((expr-tmap-assoc! t k v) (expr-TMap kt vt))
     (let ([rt (checkQ ctx t (expr-TMap kt vt))]
           [rk (checkQ ctx k kt)]
           [rv (checkQ ctx v vt)])
       (match* (rt rk rv)
         [((bu #t u1) (bu #t u2) (bu #t u3))
          (bu #t (add-usage u1 (add-usage u2 u3)))]
         [(_ _ _) (bu #f (zero-usage n))]))]
    [((expr-tset-insert! t a) (expr-TSet a-ty))
     (let ([rt (checkQ ctx t (expr-TSet a-ty))]
           [ra (checkQ ctx a a-ty)])
       (match* (rt ra)
         [((bu #t u1) (bu #t u2))
          (bu #t (add-usage u1 u2))]
         [(_ _) (bu #f (zero-usage n))]))]

    ;; ---- PropNetwork runtime wrappers: check against type constructors ----
    [((expr-prop-network _) (expr-net-type)) (bu #t (zero-usage n))]
    [((expr-cell-id _) (expr-cell-id-type)) (bu #t (zero-usage n))]
    [((expr-prop-id _) (expr-prop-id-type)) (bu #t (zero-usage n))]

    ;; ---- UnionFind runtime wrapper ----
    [((expr-uf-store _) (expr-uf-type)) (bu #t (zero-usage n))]

    ;; ---- ATMS runtime wrappers ----
    [((expr-atms-store _) (expr-atms-type)) (bu #t (zero-usage n))]
    [((expr-assumption-id-val _) (expr-assumption-id-type)) (bu #t (zero-usage n))]

    ;; ---- Tabling runtime wrapper ----
    [((expr-table-store-val _) (expr-table-store-type)) (bu #t (zero-usage n))]

    ;; ---- Relational runtime wrapper ----
    [((expr-solver-config _) (expr-solver-type)) (bu #t (zero-usage n))]

    ;; ---- Union type: checkQ(G, e, A | B) ----
    ;; Phase 5: speculative rollback with network fork/restore.
    [(_ (expr-union l r))
     (let ([rl (with-speculative-rollback
                 (lambda () (checkQ ctx e l))
                 (lambda (r) (and (bu? r) (bu-ok? r)))
                 "union-checkQ-left")])
       (or rl (checkQ ctx e r)))]

    ;; ---- Conversion fallback ----
    ;; Phase 3e: added cumulativity + within-family subtyping (consistent with check)
    [(_ _)
     (let ([r (inferQ ctx e)])
       (match r
         [(tu t1 u)
          (if (and (not (expr-error? t1))
                   (or (unify-ok? (unify ctx t t1))
                       (match* ((whnf t) (whnf t1))
                         [((expr-Type l1) (expr-Type l2))
                          (level<=? l2 l1)]
                         [(t-w t1-w) (subtype? t1-w t-w)])))
              (bu #t u)
              (bu #f (zero-usage n)))]
         [_ (bu #f (zero-usage n))]))]))

;; ========================================
;; Top-level QTT check: verify all usages in a closed term
;; ========================================
(define (checkQ-top ctx e t)
  (let ([r (checkQ ctx e t)])
    (match r
      [(bu #t u) (check-all-usages ctx u)]
      [_ #f])))
