#lang racket/base

;;;
;;; PROLOGOS QTT
;;; Quantitative Type Theory: multiplicity tracking layered on top of core typing.
;;; Direct translation of prologos-qtt.maude.
;;;
;;; The QTT layer tracks how each variable is used (0, 1, or ω times)
;;; and verifies that actual usage is compatible with declared multiplicities.
;;;
;;; UsageCtx: a list of multiplicities parallel to Context, where position k
;;; records how many times bvar(k) has been used.
;;;
;;; inferQ(ctx, e) -> TypeUsage(type, usage)  or tu-error
;;; checkQ(ctx, e, T) -> BoolUsage(bool, usage)
;;;

(require racket/match
         racket/list
         "prelude.rkt"
         "syntax.rkt"
         "substitution.rkt"
         "reduction.rkt"
         "unify.rkt"
         "typing-core.rkt"
         "metavar-store.rkt")

(provide
 ;; Usage context operations
 zero-usage single-usage add-usage scale-usage
 uhead utail ulen
 check-all-usages
 ;; Result types
 (struct-out tu) (struct-out tu-error) (struct-out bu)
 ;; QTT inference and checking
 inferQ checkQ checkQ-top)

;; ========================================
;; Usage Context: plain list of multiplicities
;; ========================================

;; Create a zero-usage context of length n
(define (zero-usage n)
  (make-list n 'm0))

;; Create a usage with m1 at position k, m0 elsewhere, length n
(define (single-usage k n)
  (for/list ([i (in-range n)])
    (if (= i k) 'm1 'm0)))

;; Pointwise addition of usage contexts
(define (add-usage u1 u2)
  (cond
    [(and (null? u1) (null? u2)) '()]
    [(null? u1) u2]
    [(null? u2) u1]
    [else (cons (mult-add (car u1) (car u2))
                (add-usage (cdr u1) (cdr u2)))]))

;; Scalar multiplication of usage context
(define (scale-usage m u)
  (map (lambda (x) (mult-mul m x)) u))

;; Head and tail
(define (uhead u) (car u))
(define (utail u) (cdr u))

;; Length
(define (ulen u) (length u))

;; ========================================
;; Check that actual usages are compatible with declared multiplicities
;; ========================================
(define (check-all-usages ctx usage)
  (cond
    [(and (null? ctx) (null? usage)) #t]
    [(or (null? ctx) (null? usage)) #f]
    [else
     (let ([decl-mult (cdar ctx)]   ; multiplicity from context binding
           [actual (car usage)])
       (and (compatible decl-mult actual)
            (check-all-usages (cdr ctx) (cdr usage))))]))

;; ========================================
;; Result types for QTT inference and checking
;; ========================================
(struct tu (type usage) #:transparent)       ; type + usage
(struct tu-error () #:transparent)           ; inference failed
(struct bu (ok? usage) #:transparent)        ; bool + usage

;; tu-type and tu-usage are auto-generated by the struct definition.
;; For tu-error, use (match r [(tu t u) ...] [(tu-error) ...]) patterns.

;; Helper
(define (cdar x) (cdr (car x)))

;; ========================================
;; QTT inference: inferQ(ctx, e) -> TypeUsage
;; ========================================
(define (inferQ ctx e)
  (define n (ctx-len ctx))
  (match e
    ;; ---- Variable: bvar(K) uses position K exactly once ----
    [(expr-bvar k)
     (if (< k n)
         (tu (shift (+ k 1) 0 (lookup-type k ctx))
             (single-usage k n))
         (tu-error))]

    ;; ---- Free variable: cannot infer ----
    [(expr-fvar _) (tu-error)]

    ;; ---- Constants: zero usage ----
    [(expr-Type l) (tu (expr-Type (lsuc l)) (zero-usage n))]
    [(expr-Nat) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-Bool) (tu (expr-Type (lzero)) (zero-usage n))]
    [(expr-zero) (tu (expr-Nat) (zero-usage n))]
    [(expr-true) (tu (expr-Bool) (zero-usage n))]
    [(expr-false) (tu (expr-Bool) (zero-usage n))]

    ;; ---- Suc: usage from the argument ----
    [(expr-suc e1)
     (let ([r (inferQ ctx e1)])
       (match r
         [(tu (expr-Nat) u) (tu (expr-Nat) u)]
         [_ (tu-error)]))]

    ;; ---- Annotation: ann(e, T) ----
    [(expr-ann e1 t)
     (if (is-type ctx t)
         (let ([r (checkQ ctx e1 t)])
           (match r
             [(bu #t u) (tu t u)]
             [_ (tu-error)]))
         (tu-error))]

    ;; ---- Application ----
    ;; Usage = U_func + pi * U_arg
    [(expr-app e1 e2)
     (let ([r1 (inferQ ctx e1)])
       (match r1
         [(tu t1 u1)
          (match (whnf t1)
            [(expr-Pi m a b)
             (let ([r2 (checkQ ctx e2 a)])
               (match r2
                 [(bu #t u2)
                  (tu (subst 0 e2 b) (add-usage u1 (scale-usage m u2)))]
                 [_ (tu-error)]))]
            [_ (tu-error)])]
         [_ (tu-error)]))]

    ;; ---- fst ----
    [(expr-fst e1)
     (let ([r (inferQ ctx e1)])
       (match r
         [(tu t u)
          (match (whnf t)
            [(expr-Sigma a _) (tu a u)]
            [_ (tu-error)])]
         [_ (tu-error)]))]

    ;; ---- snd ----
    [(expr-snd e1)
     (let ([r (inferQ ctx e1)])
       (match r
         [(tu t u)
          (match (whnf t)
            [(expr-Sigma _ b) (tu (subst 0 (expr-fst e1) b) u)]
            [_ (tu-error)])]
         [_ (tu-error)]))]

    ;; ---- natrec ----
    ;; Usage = U_target + U_base + U_step (motive is type-level)
    [(expr-natrec mot base step target)
     (let ([r4 (checkQ ctx target (expr-Nat))])
       (match r4
         [(bu #t u4)
          (let ([r2 (checkQ ctx base (expr-app mot (expr-zero)))])
            (match r2
              [(bu #t u2)
               (let ([r3 (inferQ ctx step)])
                 (match r3
                   [(tu _ u3)
                    (tu (expr-app mot target)
                        (add-usage u4 (add-usage u2 u3)))]
                   [_ (tu-error)]))]
              [_ (tu-error)]))]
         [_ (tu-error)]))]

    ;; ---- J eliminator ----
    ;; Usage from the proof argument primarily
    [(expr-J mot base left right proof)
     (let ([r5 (inferQ ctx proof)])
       (match r5
         [(tu t5 u5)
          (match (whnf t5)
            [(expr-Eq t t1 t2)
             (if (and (unify-ok? (unify ctx t1 left)) (unify-ok? (unify ctx t2 right)))
                 (tu (expr-app (expr-app (expr-app mot left) right) proof) u5)
                 (tu-error))]
            [_ (tu-error)])]
         [_ (tu-error)]))]

    ;; ---- Fallback ----
    [_ (tu-error)]))

;; ========================================
;; QTT checking: checkQ(ctx, e, T) -> BoolUsage
;; ========================================
(define (checkQ ctx e t)
  (define n (ctx-len ctx))
  (define t-whnf (whnf t))
  (match* (e t-whnf)
    ;; ---- suc: check against Nat ----
    [((expr-suc e1) (expr-Nat))
     (let ([r (checkQ ctx e1 (expr-Nat))])
       (match r
         [(bu #t u) (bu #t u)]
         [_ (bu #f (zero-usage n))]))]

    ;; ---- Lambda: check against Pi ----
    ;; Sprint 7: mult-meta-aware — resolve mult-metas from Pi context or usage
    [((expr-lam m a body) (expr-Pi m2 t-dom b))
     (let* ([effective-m (cond
                           [(mult-meta? m) (if (mult-meta? m2) 'mw m2)]
                           [(mult-meta? m2) m]
                           [else m])]
            [mults-ok (or (mult-meta? m) (mult-meta? m2) (eq? m m2))])
       (cond
         [(not mults-ok) (bu #f (zero-usage n))]
         [(not (unify-ok? (unify ctx a t-dom))) (bu #f (zero-usage n))]
         [else
          (let ([r (checkQ (ctx-extend ctx a effective-m) body b)])
            (match r
              [(bu #t u)
               (let ([actual-usage (uhead u)])
                 ;; Sprint 7: solve mult-metas to observed usage
                 (when (and (mult-meta? m) (not (mult-meta-solved? (mult-meta-id m))))
                   (solve-mult-meta! (mult-meta-id m) actual-usage))
                 (when (and (mult-meta? m2) (not (mult-meta-solved? (mult-meta-id m2))))
                   (solve-mult-meta! (mult-meta-id m2) actual-usage))
                 (if (compatible effective-m actual-usage)
                     (bu #t (utail u))
                     (bu #f (zero-usage n))))]
              [_ (bu #f (zero-usage n))]))]))]

    ;; ---- Pair: check against Sigma ----
    [((expr-pair e1 e2) (expr-Sigma a b))
     (let ([r1 (checkQ ctx e1 a)])
       (match r1
         [(bu #t u1)
          (let ([r2 (checkQ ctx e2 (subst 0 e1 b))])
            (match r2
              [(bu #t u2) (bu #t (add-usage u1 u2))]
              [_ (bu #f (zero-usage n))]))]
         [_ (bu #f (zero-usage n))]))]

    ;; ---- refl: check against Eq ----
    [((expr-refl) (expr-Eq _ e1 e2))
     (bu (unify-ok? (unify ctx e1 e2)) (zero-usage n))]

    ;; ---- Meta expression: optimistically succeed with zero usage ----
    ;; A metavariable (from implicit arg insertion) doesn't consume resources.
    [((expr-meta _) _) (bu #t (zero-usage n))]

    ;; ---- Conversion fallback ----
    [(_ _)
     (let ([r (inferQ ctx e)])
       (match r
         [(tu t1 u)
          (if (and (not (expr-error? t1)) (unify-ok? (unify ctx t t1)))
              (bu #t u)
              (bu #f (zero-usage n)))]
         [_ (bu #f (zero-usage n))]))]))

;; ========================================
;; Top-level QTT check: verify all usages in a closed term
;; ========================================
(define (checkQ-top ctx e t)
  (let ([r (checkQ ctx e t)])
    (match r
      [(bu #t u) (check-all-usages ctx u)]
      [_ #f])))
