#lang racket/base

;; gen-iter.rkt — Generate tail-recursive iterative programs at variable N.
;;
;; Companion to gen-fib.rkt (which emits the UNROLLED let-binding form);
;; this generates the ITERATIVE form recognized by ast-to-low-pnet's
;; tail-rec lowering (Sprint E.3).
;;
;; Programs emitted are structurally constant in N — only the literal
;; init-args change. This lets us benchmark scheduler throughput on
;; networks of fixed shape across very different iteration counts.
;;
;; Usage:
;;   racket tools/gen-iter.rkt --algorithm fib --n 100 > out.prologos
;;   racket tools/gen-iter.rkt --algorithm sum --n 100 > out.prologos
;;   racket tools/gen-iter.rkt --algorithm factorial --n 10 > out.prologos
;;
;; The :expect-exit annotation reflects the result mod 256 (Linux exit
;; code convention). For N where the result overflows i64 (fib(N>=93),
;; factorial(N>=20)), exit-code prediction is best-effort.

(require racket/cmdline)

(define algorithm (make-parameter 'fib))
(define n (make-parameter 10))

(command-line
 #:program "gen-iter"
 #:once-each
 [("--algorithm") a "Algorithm: fib, sum, factorial, pair-fib, helpered-fib, sumsq, dual-acc, pell, pow2 (default fib)"
  (define sym (string->symbol a))
  (unless (memq sym '(fib sum factorial pair-fib helpered-fib sumsq dual-acc pell pow2))
    (error 'gen-iter "unknown algorithm '~a'" a))
  (algorithm sym)]
;; Sprint F.5 (2026-05-01): pell re-enabled. Its depth-2 step expression
;; (`[int+ [int* 2 b] a]`) used to fail because of mismatched BSP lags
;; between step cells. emit-aligned-propagator! and the pre-select
;; uniform lift in lower-tail-rec now insert identity bridges to align
;; all step values at the same iteration boundary.
 [("--n") k "Iteration count (default 10)"
  (define v (string->number k))
  (unless (and (exact-integer? v) (>= v 0))
    (error 'gen-iter "N must be non-negative integer; got ~v" k))
  (n v)])

;; --- Reference implementations (Racket-side, for :expect-exit) ---

(define (fib-iter k)
  (let loop ([a 0] [b 1] [i k])
    (if (<= i 0) a (loop b (+ a b) (- i 1)))))

(define (sum-iter k)
  (let loop ([acc 0] [i k])
    (if (<= i 0) acc (loop (+ acc i) (- i 1)))))

(define (factorial-iter k)
  (let loop ([acc 1] [i k])
    (if (<= i 1) acc (loop (* acc i) (- i 1)))))

;; Reference implementations for the new algorithms.
(define (sumsq-iter k)
  (let loop ([acc 0] [i k])
    (if (<= i 0) acc (loop (+ acc (* i i)) (- i 1)))))

(define (dual-acc-iter k)
  (let loop ([s 0] [p 1] [i k])
    (if (<= i 0) (+ s p) (loop (+ s i) (* p i) (- i 1)))))

(define (pell-iter k)
  (let loop ([a 0] [b 1] [i k])
    (if (<= i 0) a (loop b (+ (* 2 b) a) (- i 1)))))

(define (pow2-iter k)
  (let loop ([acc 1] [i k])
    (if (<= i 0) acc (loop (* acc 2) (- i 1)))))

(define expected-result
  (case (algorithm)
    [(fib pair-fib helpered-fib) (fib-iter (n))]
    [(sum)                       (sum-iter (n))]
    [(factorial)                 (factorial-iter (n))]
    [(sumsq)                     (sumsq-iter (n))]
    [(dual-acc)                  (dual-acc-iter (n))]
    [(pell)                      (pell-iter (n))]
    [(pow2)                      (pow2-iter (n))]))

;; i64 wrap then mod 256 for exit code. Two-step because Racket integers
;; are arbitrary precision; for overflow correctness we explicitly wrap
;; at i64 first.
(define (wrap-i64 x)
  (define unwrapped (bitwise-and x #xffffffffffffffff))
  (if (>= unwrapped #x8000000000000000)
      (- unwrapped #x10000000000000000)
      unwrapped))

(define expected-exit (modulo (wrap-i64 expected-result) 256))

;; --- Source emission ---

(case (algorithm)
  [(fib)
   (printf ";; Iterative fib(~a) — auto-generated by tools/gen-iter.rkt~n" (n))
   (printf ";; expected fib(~a) = ~a; exit code (mod 256) = ~a~n"
           (n) expected-result expected-exit)
   (printf ";; :expect-exit ~a~n" expected-exit)
   (newline)
   (printf "spec fib-iter Int -> Int -> Int -> Int~n")
   (printf "defn fib-iter [a b n]~n")
   (printf "  match [int-lt n 1]~n")
   (printf "    | true  -> a~n")
   (printf "    | false -> [fib-iter b [int+ a b] [int- n 1]]~n")
   (newline)
   (printf "def main : Int := [fib-iter 0 1 ~a]~n" (n))]

  [(sum)
   (printf ";; Iterative sum 1..N for N=~a — auto-generated by tools/gen-iter.rkt~n" (n))
   (printf ";; expected sum(~a) = ~a; exit code (mod 256) = ~a~n"
           (n) expected-result expected-exit)
   (printf ";; :expect-exit ~a~n" expected-exit)
   (newline)
   (printf "spec sum-to Int -> Int -> Int~n")
   (printf "defn sum-to [acc n]~n")
   (printf "  match [int-lt n 1]~n")
   (printf "    | true  -> acc~n")
   (printf "    | false -> [sum-to [int+ acc n] [int- n 1]]~n")
   (newline)
   (printf "def main : Int := [sum-to 0 ~a]~n" (n))]

  [(factorial)
   (printf ";; Iterative factorial(~a) — auto-generated by tools/gen-iter.rkt~n" (n))
   (printf ";; expected ~a! = ~a; exit code (mod 256) = ~a~n"
           (n) expected-result expected-exit)
   (printf ";; :expect-exit ~a~n" expected-exit)
   (newline)
   (printf "spec factorial-iter Int -> Int -> Int~n")
   (printf "defn factorial-iter [acc n]~n")
   (printf "  match [int-le n 1]~n")
   (printf "    | true  -> acc~n")
   (printf "    | false -> [factorial-iter [int* acc n] [int- n 1]]~n")
   (newline)
   (printf "def main : Int := [factorial-iter 1 ~a]~n" (n))]

  [(pair-fib)
   ;; Pair-state fib: state is a single <Int * Int> carrying (a, b)
   ;; PLUS a counter n. Same fib computation as `fib` but encoded
   ;; with pair-typed state (Sprint F.3). Should produce identical
   ;; metrics to plain `fib` since per-leaf decomposition is
   ;; equivalent to multi-binder encoding.
   (printf ";; Pair-state fib(~a) — auto-generated by tools/gen-iter.rkt~n" (n))
   (printf ";; expected fib(~a) = ~a; exit code (mod 256) = ~a~n"
           (n) expected-result expected-exit)
   (printf ";; :expect-exit ~a~n" expected-exit)
   (newline)
   (printf "spec fib-pair <Int * Int> -> Int -> Int~n")
   (printf "defn fib-pair [p n]~n")
   (printf "  match [int-lt n 1]~n")
   (printf "    | true  -> [fst p]~n")
   (printf "    | false -> [fib-pair [pair [snd p] [int+ [fst p] [snd p]]] [int- n 1]]~n")
   (newline)
   (printf "def main : Int := [fib-pair [pair 0 1] ~a]~n" (n))]

  [(helpered-fib)
   ;; Helpered fib: factors out the step expression into a separate
   ;; helper `next-fib` that returns a pair. Tail-rec body inlines
   ;; the helper (Sprint F.1). Tests composition of inlining + pair
   ;; lowering + tail-rec.
   (printf ";; Helpered fib(~a) — auto-generated by tools/gen-iter.rkt~n" (n))
   (printf ";; expected fib(~a) = ~a; exit code (mod 256) = ~a~n"
           (n) expected-result expected-exit)
   (printf ";; :expect-exit ~a~n" expected-exit)
   (newline)
   (printf "spec next-fib <Int * Int> -> <Int * Int>~n")
   (printf "defn next-fib [p] [pair [snd p] [int+ [fst p] [snd p]]]~n")
   (newline)
   (printf "spec fib-with-helper <Int * Int> -> Int -> Int~n")
   (printf "defn fib-with-helper [p n]~n")
   (printf "  match [int-lt n 1]~n")
   (printf "    | true  -> [fst p]~n")
   (printf "    | false -> [fib-with-helper [next-fib p] [int- n 1]]~n")
   (newline)
   (printf "def main : Int := [fib-with-helper [pair 0 1] ~a]~n" (n))]

  [(sumsq)
   ;; Sum of squares Σ k² for k=1..N. Single accumulator. Each
   ;; iteration multiplies n*n then adds to acc — exercises int-mul
   ;; in the iteration body (fib uses only int-add).
   (printf ";; Sum of squares Σk² for N=~a — auto-generated~n" (n))
   (printf ";; expected = ~a; exit code (mod 256) = ~a~n"
           expected-result expected-exit)
   (printf ";; :expect-exit ~a~n" expected-exit)
   (newline)
   (printf "spec sumsq Int -> Int -> Int~n")
   (printf "defn sumsq [acc n]~n")
   (printf "  match [int-lt n 1]~n")
   (printf "    | true  -> acc~n")
   (printf "    | false -> [sumsq [int+ acc [int* n n]] [int- n 1]]~n")
   (newline)
   (printf "def main : Int := [sumsq 0 ~a]~n" (n))]

  [(dual-acc)
   ;; Dual accumulator (sum + product simultaneously) via pair-state.
   ;; <s; p> evolves as <s+i; p*i> until i hits 0; result = s + p.
   ;; Demonstrates the F.3 sweet spot: structured state where the
   ;; two slots accumulate independently.
   (printf ";; Dual accumulator (Σi + Πi) for N=~a — auto-generated~n" (n))
   (printf ";; expected = ~a; exit code (mod 256) = ~a~n"
           expected-result expected-exit)
   (printf ";; :expect-exit ~a~n" expected-exit)
   (newline)
   (printf "spec dual-acc <Int * Int> -> Int -> Int~n")
   (printf "defn dual-acc [sp i]~n")
   (printf "  match [int-lt i 1]~n")
   (printf "    | true  -> [int+ [fst sp] [snd sp]]~n")
   (printf "    | false -> [dual-acc [pair [int+ [fst sp] i] [int* [snd sp] i]] [int- i 1]]~n")
   (newline)
   (printf "def main : Int := [dual-acc [pair 0 1] ~a]~n" (n))]

  [(pell)
   ;; Pell numbers: P(n) = 2*P(n-1) + P(n-2). Depth-2 step expression
   ;; `[int+ [int* 2 b] a]` requires F.5's lag-matching bridges.
   (printf ";; Pell P(~a) — auto-generated~n" (n))
   (printf ";; expected = ~a; exit code (mod 256) = ~a~n"
           expected-result expected-exit)
   (printf ";; :expect-exit ~a~n" expected-exit)
   (newline)
   (printf "spec pell-iter Int -> Int -> Int -> Int~n")
   (printf "defn pell-iter [a b n]~n")
   (printf "  match [int-lt n 1]~n")
   (printf "    | true  -> a~n")
   (printf "    | false -> [pell-iter b [int+ [int* 2 b] a] [int- n 1]]~n")
   (newline)
   (printf "def main : Int := [pell-iter 0 1 ~a]~n" (n))]

  [(pow2)
   ;; 2^N via repeated doubling. Single accumulator; tests int-mul
   ;; only.
   (printf ";; 2^~a — auto-generated~n" (n))
   (printf ";; expected = ~a; exit code (mod 256) = ~a~n"
           expected-result expected-exit)
   (printf ";; :expect-exit ~a~n" expected-exit)
   (newline)
   (printf "spec pow2 Int -> Int -> Int~n")
   (printf "defn pow2 [acc n]~n")
   (printf "  match [int-lt n 1]~n")
   (printf "    | true  -> acc~n")
   (printf "    | false -> [pow2 [int* acc 2] [int- n 1]]~n")
   (newline)
   (printf "def main : Int := [pow2 1 ~a]~n" (n))])
