#lang racket/base

;; gen-iter.rkt — Generate tail-recursive iterative programs at variable N.
;;
;; Companion to gen-fib.rkt (which emits the UNROLLED let-binding form);
;; this generates the ITERATIVE form recognized by ast-to-low-pnet's
;; tail-rec lowering (Sprint E.3).
;;
;; Programs emitted are structurally constant in N — only the literal
;; init-args change. This lets us benchmark scheduler throughput on
;; networks of fixed shape across very different iteration counts.
;;
;; Usage:
;;   racket tools/gen-iter.rkt --algorithm fib --n 100 > out.prologos
;;   racket tools/gen-iter.rkt --algorithm sum --n 100 > out.prologos
;;   racket tools/gen-iter.rkt --algorithm factorial --n 10 > out.prologos
;;
;; The :expect-exit annotation reflects the result mod 256 (Linux exit
;; code convention). For N where the result overflows i64 (fib(N>=93),
;; factorial(N>=20)), exit-code prediction is best-effort.

(require racket/cmdline)

(define algorithm (make-parameter 'fib))
(define n (make-parameter 10))

(command-line
 #:program "gen-iter"
 #:once-each
 [("--algorithm") a "Algorithm: fib, sum, factorial (default fib)"
  (define sym (string->symbol a))
  (unless (memq sym '(fib sum factorial))
    (error 'gen-iter "unknown algorithm '~a' (expected fib, sum, factorial)" a))
  (algorithm sym)]
 [("--n") k "Iteration count (default 10)"
  (define v (string->number k))
  (unless (and (exact-integer? v) (>= v 0))
    (error 'gen-iter "N must be non-negative integer; got ~v" k))
  (n v)])

;; --- Reference implementations (Racket-side, for :expect-exit) ---

(define (fib-iter k)
  (let loop ([a 0] [b 1] [i k])
    (if (<= i 0) a (loop b (+ a b) (- i 1)))))

(define (sum-iter k)
  (let loop ([acc 0] [i k])
    (if (<= i 0) acc (loop (+ acc i) (- i 1)))))

(define (factorial-iter k)
  (let loop ([acc 1] [i k])
    (if (<= i 1) acc (loop (* acc i) (- i 1)))))

(define expected-result
  (case (algorithm)
    [(fib)       (fib-iter (n))]
    [(sum)       (sum-iter (n))]
    [(factorial) (factorial-iter (n))]))

;; i64 wrap then mod 256 for exit code. Two-step because Racket integers
;; are arbitrary precision; for overflow correctness we explicitly wrap
;; at i64 first.
(define (wrap-i64 x)
  (define unwrapped (bitwise-and x #xffffffffffffffff))
  (if (>= unwrapped #x8000000000000000)
      (- unwrapped #x10000000000000000)
      unwrapped))

(define expected-exit (modulo (wrap-i64 expected-result) 256))

;; --- Source emission ---

(case (algorithm)
  [(fib)
   (printf ";; Iterative fib(~a) — auto-generated by tools/gen-iter.rkt~n" (n))
   (printf ";; expected fib(~a) = ~a; exit code (mod 256) = ~a~n"
           (n) expected-result expected-exit)
   (printf ";; :expect-exit ~a~n" expected-exit)
   (newline)
   (printf "spec fib-iter Int -> Int -> Int -> Int~n")
   (printf "defn fib-iter [a b n]~n")
   (printf "  match [int-lt n 1]~n")
   (printf "    | true  -> a~n")
   (printf "    | false -> [fib-iter b [int+ a b] [int- n 1]]~n")
   (newline)
   (printf "def main : Int := [fib-iter 0 1 ~a]~n" (n))]

  [(sum)
   (printf ";; Iterative sum 1..N for N=~a — auto-generated by tools/gen-iter.rkt~n" (n))
   (printf ";; expected sum(~a) = ~a; exit code (mod 256) = ~a~n"
           (n) expected-result expected-exit)
   (printf ";; :expect-exit ~a~n" expected-exit)
   (newline)
   (printf "spec sum-to Int -> Int -> Int~n")
   (printf "defn sum-to [acc n]~n")
   (printf "  match [int-lt n 1]~n")
   (printf "    | true  -> acc~n")
   (printf "    | false -> [sum-to [int+ acc n] [int- n 1]]~n")
   (newline)
   (printf "def main : Int := [sum-to 0 ~a]~n" (n))]

  [(factorial)
   (printf ";; Iterative factorial(~a) — auto-generated by tools/gen-iter.rkt~n" (n))
   (printf ";; expected ~a! = ~a; exit code (mod 256) = ~a~n"
           (n) expected-result expected-exit)
   (printf ";; :expect-exit ~a~n" expected-exit)
   (newline)
   (printf "spec factorial-iter Int -> Int -> Int~n")
   (printf "defn factorial-iter [acc n]~n")
   (printf "  match [int-le n 1]~n")
   (printf "    | true  -> acc~n")
   (printf "    | false -> [factorial-iter [int* acc n] [int- n 1]]~n")
   (newline)
   (printf "def main : Int := [factorial-iter 1 ~a]~n" (n))])
