#lang racket/base

;; gen-fib.rkt — Generate fib(N) as a chain of let-bindings.
;;
;; Iterative fib without recursion: maintain (a, b) starting at (0, 1).
;; Each step: (a, b) → (b, a+b). After N steps, a = fib(N).
;;
;; Encoded as nested let-bindings via beta-redex `[(fn [name : Int] body) arg]`:
;;
;;   def main : Int :=
;;     [(fn [a0 : Int]
;;      [(fn [b0 : Int]
;;       [(fn [a1 : Int]
;;        [(fn [b1 : Int]
;;         ... aN)
;;         [int+ a_{N-1} b_{N-1}]])
;;        b_{N-1}])
;;       1])
;;      0]
;;
;; Note the trailing `)` to close (fn) before the application's arg+]:
;;   [(fn [name : Int] body) arg]
;;
;; Usage: racket tools/gen-fib.rkt N > out.prologos
;; Run via: racket tools/pnet-compile.rkt out.prologos

(require racket/cmdline)

(define n
  (let ([s (command-line #:program "gen-fib" #:args (n) n)])
    (or (string->number s)
        (error 'gen-fib "expected non-negative integer argument; got ~v" s))))

(unless (and (exact-integer? n) (>= n 0))
  (error 'gen-fib "N must be a non-negative integer; got ~v" n))

;; Compute fib(N) and the byte-truncated exit code.
(define (fib n)
  (let loop ([a 0] [b 1] [k 0])
    (if (= k n) a (loop b (+ a b) (+ k 1)))))

(define expected-exit (modulo (fib n) 256))

(displayln (format ";; Iterative fib(~a) — auto-generated by tools/gen-fib.rkt" n))
(displayln (format ";; fib(~a) = ~a; exit code (mod 256) = ~a"
                   n (fib n) expected-exit))
(displayln (format ";; :expect-exit ~a" expected-exit))
(newline)

;; Emit as ONE LONG LINE for parser predictability. WS-mode in Prologos
;; can be picky about indentation across multiple bindings; collapsing
;; to one line removes that as a variable.
;;
;; Structure: a chain of `[(fn [name : Int] BODY) ARG]` where BODY is
;; the next nested binding and ARG is this binding's value.
;;
;; Bindings, outermost-first:
;;   a0 = 0
;;   b0 = 1
;;   a1 = b0           (innermost reads previous b)
;;   b1 = a0 + b0      (innermost reads previous a, b)
;;   a2 = b1
;;   b2 = a1 + b1
;;   ...
;;   aN = b_{N-1}
;;   bN = a_{N-1} + b_{N-1}
;; Innermost body returns aN.

(display "def main : Int := ")

;; Emit all openers (left side of each binding).
(display "[(fn [a0 : Int] ")
(display "[(fn [b0 : Int] ")
(for ([i (in-range 1 (+ n 1))])
  (display (format "[(fn [a~a : Int] " i))
  (display (format "[(fn [b~a : Int] " i)))

;; Innermost body
(display (format "a~a" n))

;; Emit closers (right side: `) arg]` for each binding, innermost-first).
;; Innermost is bN with arg = a_{N-1} + b_{N-1}; then aN with arg = b_{N-1};
;; … out to b0 with arg = 1; a0 with arg = 0.
(for ([i (in-range n 0 -1)])
  (display (format ") [int+ a~a b~a]]" (- i 1) (- i 1)))
  (display (format ") b~a]" (- i 1))))
(display ") 1]")
(display ") 0]")
(newline)
