#lang racket/base

;; gen-fact-corpus.rkt — Generate WS-mode .prologos fact-relation corpora
;; (Rel T1 Aspect D, D.2.c — the artifact §8 dataset generator).
;;
;; Emits a `.prologos` file (or string) containing:
;;   - `defr` fact relations at a requested row count / arity
;;     (multi-LINE `||` rows — one-line multi-row fact literals parse as a
;;      single wrong-arity row; see dailies 2026-07-19 "WS-syntax probe
;;      discipline")
;;   - an `edge` relation + `path` rule (2-hop join shape)
;;   - point / partial / enumeration / membership / join solve queries
;;
;; This is the pragmatic route to E2E fact-scale inputs until the `:from` /
;; `:source` bulk-import surface exists (artifact §3.2, Rel T2 pillar 2):
;; there is currently NO other way to get >16 rows into a relation from a
;; `.prologos` file.
;;
;; Library use:  (gen-fact-corpus-string #:rows 250 ...)
;; CLI use:      racket tools/gen-fact-corpus.rkt --rows 250 --out FILE.prologos

(require racket/cmdline
         racket/string)

(provide gen-fact-corpus-string)

;; Deterministic value for row i, column c (no randomness — reproducible,
;; and Date/Math.random-free by design).
(define (cell-value i c)
  (case c
    [(0) (number->string i)]                          ;; dense int key
    [(1) (format "\"n~a\"" i)]                        ;; string column
    [else (number->string (* (+ c 5) i))]))           ;; derived ints

;; Fact block: ONE `||` opens the block; continuation rows are aligned values
;; with NO repeated `||` (the acceptance-file style — a per-line `||` or a
;; one-line multi-row literal both mis-parse; see dailies 2026-07-19).
(define (fact-row-string i arity)
  (string-join (for/list ([c (in-range arity)]) (cell-value i c)) " "))

(define (fact-block n-rows arity)
  (string-join
   (for/list ([i (in-range n-rows)])
     (if (zero? i)
         (format "  || ~a" (fact-row-string i arity))
         (format "     ~a" (fact-row-string i arity))))
   "\n"))

;; Build the corpus as a string.
;; rows: fact count for the `data` relation.
;; arity: column count for `data` (>= 2).
;; edge-rows: fact count for the `edge` relation feeding the `path` join.
(define (gen-fact-corpus-string #:rows [rows 100]
                                #:arity [arity 3]
                                #:edge-rows [edge-rows 50]
                                #:ns-name [ns-name 'factscale])
  (define params
    (string-join (for/list ([c (in-range arity)]) (format "?c~a" c)) " "))
  (define data-block (fact-block rows arity))
  ;; edge i -> i+1 chain (join-friendly; `path` finds 2-hop pairs)
  (define edge-block
    (string-join
     (for/list ([i (in-range edge-rows)])
       (if (zero? i)
           (format "  || ~a ~a" i (add1 i))
           (format "     ~a ~a" i (add1 i))))
     "\n"))
  (define last-key (number->string (sub1 rows)))
  (define last-str (format "\"n~a\"" (sub1 rows)))
  ;; Query-site vars are BARE (no ?) and must match the relation's ARITY —
  ;; the engine is arity-LENIENT: a wrong-arity solve silently returns nil
  ;; (dailies 2026-07-19 Watching 2b), so these are generated, never hardcoded.
  (define (qvars from) (for/list ([c (in-range from arity)]) (format "a~a" c)))
  (define (spaced xs) (string-join xs " "))
  (string-append
   (format "ns ~a\n\n" ns-name)
   ";; GENERATED by tools/gen-fact-corpus.rkt — do not hand-edit.\n"
   (format ";; rows=~a arity=~a edge-rows=~a\n\n" rows arity edge-rows)
   (format "defr data [~a]\n~a\n\n" params data-block)
   "defr edge [?a ?b]\n" edge-block "\n\n"
   "defr path [?x ?z]\n  &> (edge x y) (edge y z)\n\n"
   ";; Query shapes (artifact §8)\n"
   (format "solve (data ~a ~a)\n" last-key (spaced (qvars 1)))   ;; ground-key point, last row
   (format "solve (data ~a)\n" (spaced (qvars 0)))               ;; all-free enumeration
   (format "solve (data a0 ~a ~a)\n" last-str (spaced (qvars 2))) ;; partial key (2nd col ground)
   ;; All-ground membership (hit on the LAST row, then a miss). Tier-1 DECLINES
   ;; fully-ground queries, so at rows ≥ the :auto threshold (256) these are
   ;; the queries that actually reach the ON-NETWORK engine E2E.
   (format "solve (data ~a)\n" (spaced (for/list ([c (in-range arity)]) (cell-value (sub1 rows) c))))
   (format "solve (data -1 ~a)\n" (spaced (for/list ([c (in-range 1 arity)]) "\"nope\"")))
   "solve (path x z)\n"))                                        ;; 2-hop join

(module+ main
  (define rows 100)
  (define arity 3)
  (define edge-rows 50)
  (define out-path #f)
  (command-line
   #:program "gen-fact-corpus"
   #:once-each
   [("--rows") n "Fact rows for `data` (default 100)" (set! rows (string->number n))]
   [("--arity") a "Columns for `data` (default 3)" (set! arity (string->number a))]
   [("--edge-rows") e "Rows for `edge` (default 50)" (set! edge-rows (string->number e))]
   [("--out") p "Output path (default stdout)" (set! out-path p)])
  (define s (gen-fact-corpus-string #:rows rows #:arity arity #:edge-rows edge-rows))
  (if out-path
      (call-with-output-file out-path (lambda (o) (display s o)) #:exists 'replace)
      (display s)))
