#lang racket/base

;;; Tests for SRE Track 2I Phase 3 — Property Sweep
;;;
;;; The Phase 3 sweep validates Phase 3c's distributivity-flip discovery
;;; (currently confirmed only on hand-picked-6 atoms) against the wider
;;; Phase 2a-generator sample space (compounds + non-dependent binders).
;;;
;;; Per design doc § Phase 3 Locked decisions (2026-04-30):
;;;   - sweep is generic; atoms supplied by caller (realistic-type-atoms here)
;;;   - {distributive, sd-vee, sd-wedge} run together per (domain, relation)
;;;   - sd-finding records carry sd-evidence (SD) or axiom-* (distributive)
;;;
;;; Per PTF Lattice Hierarchy note §5.1 — confirming distributive on the
;;; wider sample space unlocks Discussion-phase declaration → DNF
;;; canonicalization, Birkhoff representation, clean Galois bridge composition
;;; with type×subtype (which is also at distributive level via Track 2H Heyting decl).
;;;
;;; PERF DECOUPLING (drift risk #5 named at mini-design materialized as predicted):
;;; the sweep is O(N³) per check × 6 checks. At depth-1 with 50+ samples, one
;;; sweep takes >50 seconds — pathological for the suite. Resolution:
;;;
;;;   - Tests use depth-0 sample (bot + top + 4 base atoms = 6 samples).
;;;     216 triples × 6 checks runs in <2 seconds. Validates the sweep
;;;     MECHANISM works correctly: returns sd-finding records, determines
;;;     distributive status, format-sd-findings produces markdown.
;;;     At depth-0 my sweep exactly reproduces the Phase 3c hand-picked-6
;;;     check (216/216 confirmed), so this IS a regression of that finding.
;;;
;;;   - Wider-sample findings (depth-1, ~50 samples, compounds + binders)
;;;     are produced by `racket sre-property-sweep.rkt` — a one-off
;;;     invocation that prints the markdown findings table. Output is
;;;     captured into design doc § Phase 3 Findings as a versioned artifact,
;;;     NOT regenerated by the test suite.
;;;
;;; Honest separation: tests = regression that machine works. Findings table
;;; = captured artifact. Both axes covered, neither penalizes suite time.
;;;
;;; SHARED FIXTURE (per testing.md): single sweep at module load, all
;;; test-cases reference cached findings. File in its own test file so even
;;; the small-sample sweep cost doesn't penalize the broader algebraic suite.
;;;
;;; This is the early Phase T realization: Phase T (per workflow.md MANDATORY
;;; dedicated test phase) will EXPAND this with golden fixtures, broader
;;; coverage, and counterexample regression tests when bonus findings surface.

(require rackunit
         racket/list
         racket/string
         "../driver.rkt"          ;; loads both domains via register-domain!
         "../sre-core.rkt"
         "../sre-property-sweep.rkt"
         "../syntax.rkt")

;; ============================================================================
;; Shared fixture: the Phase 3 sweep runs ONCE at module load
;; ============================================================================
;; Caller-supplied atoms per Q2 design decision (sweep stays generic).
;; Same set as test-sre-algebraic's `realistic-type-atoms`, redefined here
;; to keep this file self-contained (intentional duplication; both lists
;; are short and stable).

(define realistic-type-atoms
  (list (expr-Int) (expr-Bool) (expr-Nat) (expr-String)))

(define type-domain-for-sweep (lookup-domain 'type))

;; depth-0: bot + top + 4 base atoms = 6 samples; 216 triples × 6 checks ~ 2 sec.
;; This exactly reproduces the Phase 3c hand-picked-6 check via the sweep
;; mechanism — regression test for the same finding through a different lens.
(define phase3-findings
  (run-sd-sweep type-domain-for-sweep
                '(equality subtype)
                realistic-type-atoms
                #:max-depth 0))

(define (find-finding rel prop)
  (findf (lambda (f)
           (and (eq? (sd-finding-relation f) rel)
                (eq? (sd-finding-property f) prop)))
         phase3-findings))

;; ============================================================================
;; Shape and sanity tests
;; ============================================================================

(test-case "Phase 3: run-sd-sweep returns 6 findings (3 properties × 2 relations)"
  (check-equal? (length phase3-findings) 6))

(test-case "Phase 3: each finding has correct shape"
  (for ([f (in-list phase3-findings)])
    (check-true (sd-finding? f))
    (check-eq? (sd-finding-domain-name f) 'type)
    (check-true (memq (sd-finding-relation f) '(equality subtype)))
    (check-true (memq (sd-finding-property f) '(distributive sd-vee sd-wedge)))
    (check-true (positive? (sd-finding-sample-count f)))))

(test-case "Phase 3: distributive findings carry axiom-*; SD findings carry sd-evidence"
  (for ([f (in-list phase3-findings)])
    (define ev (sd-finding-evidence f))
    (case (sd-finding-property f)
      [(distributive)
       (check-true (or (axiom-confirmed? ev)
                       (axiom-refuted? ev)
                       (eq? ev axiom-untested)))]
      [(sd-vee sd-wedge)
       (check-true (sd-evidence? ev))])))

;; ============================================================================
;; The load-bearing assertions: distributivity-flip validation on wider sample
;; ============================================================================

(test-case "Phase 3: type×equality is distributive on wider sample (validates Phase 3c flip)"
  ;; Phase 3c confirmed distributive on hand-picked-6 (216/216 triples).
  ;; Phase 3 validates on the Phase 2a-generator sample space (compounds +
  ;; non-dependent binders). This is the load-bearing finding for the
  ;; Discussion phase declaration update.
  (define f (find-finding 'equality 'distributive))
  (check-not-false f)
  (check-true (axiom-confirmed? (sd-finding-evidence f))
              "type×equality should be distributive on wider sample"))

(test-case "Phase 3: type×equality SD-vee and SD-wedge inherited from distributive"
  ;; Implication chain: distributive ⇒ sd-vee ∧ sd-wedge (Phase 1).
  ;; If distributive confirms, both SD checks should also confirm.
  (for ([prop '(sd-vee sd-wedge)])
    (define f (find-finding 'equality prop))
    (check-not-false f)
    (check-eq? (sd-evidence-status (sd-finding-evidence f)) 'confirmed
               (format "type×equality ~a should be confirmed" prop))))

(test-case "Phase 3: type×subtype is distributive on wider sample (validates Track 2H Heyting decl)"
  ;; Track 2H declared has-pseudo-complement → distributive.
  ;; Phase 3 validates on wider sample.
  (define f (find-finding 'subtype 'distributive))
  (check-not-false f)
  (check-true (axiom-confirmed? (sd-finding-evidence f))
              "type×subtype should be distributive on wider sample (Track 2H decl)"))

;; ============================================================================
;; Format function tests
;; ============================================================================

(test-case "Phase 3: format-sd-findings produces well-formed markdown"
  (define md (format-sd-findings phase3-findings))
  (define lines (string-split md "\n"))
  ;; Header + separator + 6 finding rows = 8 lines
  (check-equal? (length lines) 8)
  ;; Header has expected columns
  (check-true (string-contains? (first lines) "Domain"))
  (check-true (string-contains? (first lines) "Property"))
  (check-true (string-contains? (first lines) "Non-vacuity"))
  ;; Separator is markdown table separator
  (check-true (string-prefix? (second lines) "|---"))
  ;; All rows start with `|` and contain `type`
  (for ([line (in-list (drop lines 2))])
    (check-true (string-prefix? line "|"))
    (check-true (string-contains? line "type"))))

(test-case "Phase 3: non-vacuity ratio reported per finding (counts are sane)"
  (for ([prop '(sd-vee sd-wedge)])
    (for ([rel '(equality subtype)])
      (define f (find-finding rel prop))
      (define ev (sd-finding-evidence f))
      (define total (sd-evidence-total-checked ev))
      (define fired (sd-evidence-hypothesis-fired ev))
      (define held  (sd-evidence-conclusion-held ev))
      (check-true (positive? total))
      (check-true (<= 0 fired total))
      (check-true (<= 0 held fired)))))
